{
  "openapi": "3.0.0",
  "info": {
    "title": "GoHighLevel API v2 - Unified",
    "description": "Unified OpenAPI specification for the GoHighLevel API v2. Auto-generated by merging all individual API module specs from the official GoHighLevel/highlevel-api-docs repository.",
    "version": "2.0.0",
    "contact": {
      "name": "GoHighLevel Developer Docs",
      "url": "https://marketplace.gohighlevel.com/docs/oauth/GettingStarted"
    }
  },
  "servers": [
    {
      "url": "https://services.leadconnectorhq.com",
      "description": "GoHighLevel API v2"
    }
  ],
  "paths": {
    "/associations/relations": {
      "post": {
        "operationId": "create-relation",
        "summary": "Create Relation for you associated entities.",
        "description": "Create Relation.Documentation Link - https://doc.clickup.com/8631005/d/h/87cpx-293776/cd0f4122abc04d3",
        "tags": [
          "Relations"
        ],
        "security": [
          {
            "bearer": [
              "associations/relation.write"
            ]
          }
        ]
      }
    },
    "/associations/relations/{recordId}": {
      "get": {
        "operationId": "get-relations-by-record-id",
        "summary": "Get all relations By record Id",
        "description": "Get all relations by record Id",
        "tags": [
          "Relations"
        ],
        "security": [
          {
            "bearer": [
              "associations/relation.readonly"
            ]
          }
        ]
      }
    },
    "/associations/relations/{relationId}": {
      "delete": {
        "operationId": "delete-relation",
        "summary": "Delete Relation",
        "description": "Delete Relation",
        "tags": [
          "Relations"
        ],
        "security": [
          {
            "bearer": [
              "associations/relation.write"
            ]
          }
        ]
      }
    },
    "/associations/key/{key_name}": {
      "get": {
        "operationId": "get-association-key-by-key-name",
        "summary": "Get association key by key name",
        "description": "Using this api you can get standard / user defined association by key",
        "tags": [
          "Associations"
        ],
        "security": [
          {
            "bearer": [
              "associations.readonly"
            ]
          }
        ]
      }
    },
    "/associations/objectKey/{objectKey}": {
      "get": {
        "operationId": "get-association-by-object-keys",
        "summary": "Get association by object keys",
        "description": "Get association by object keys like contacts, custom objects and opportunities. Documentation Link - https://doc.clickup.com/8631005/d/h/87cpx-293776/cd0f4122abc04d3",
        "tags": [
          "Associations"
        ],
        "security": [
          {
            "bearer": [
              "associations.readonly"
            ]
          }
        ]
      }
    },
    "/associations/{associationId}": {
      "put": {
        "operationId": "update-association",
        "summary": "Update Association By Id",
        "description": "Update Association , Allows you to update labels of an associations. Documentation Link - https://doc.clickup.com/8631005/d/h/87cpx-293776/cd0f4122abc04d3",
        "tags": [
          "Associations"
        ],
        "security": [
          {
            "bearer": [
              "associations.write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete-association",
        "summary": "Delete Association",
        "description": "Delete USER_DEFINED Association By Id, deleting an association will also all the relations for that association",
        "tags": [
          "Associations"
        ],
        "security": [
          {
            "bearer": [
              "associations.write"
            ]
          }
        ]
      },
      "get": {
        "operationId": "get-association-by-ID",
        "summary": "Get association by ID",
        "description": "Using this api you can get SYSTEM_DEFINED / USER_DEFINED association by id ",
        "tags": [
          "Associations"
        ],
        "security": [
          {
            "bearer": [
              "associations.readonly"
            ]
          }
        ]
      }
    },
    "/associations/": {
      "post": {
        "operationId": "create-association",
        "summary": "Create Association",
        "description": "Allow you to create contact - contact , contact - custom objects associations, will add more in the future.Documentation Link - https://doc.clickup.com/8631005/d/h/87cpx-293776/cd0f4122abc04d3",
        "tags": [
          "Associations"
        ],
        "security": [
          {
            "bearer": [
              "associations.write"
            ]
          }
        ]
      },
      "get": {
        "operationId": "find-associations",
        "summary": "Get all associations for a sub-account / location",
        "description": "Get all Associations",
        "tags": [
          "Associations"
        ],
        "security": [
          {
            "bearer": [
              "associations.readonly"
            ]
          }
        ]
      }
    },
    "/blogs/posts/url-slug-exists": {
      "get": {
        "operationId": "check-url-slug-exists",
        "summary": "Check url slug",
        "description": "The \"Check url slug\" API allows check the blog slug validation which is needed before publishing any blog post. Please use blogs/check-slug.readonly. you can find the POST ID from the post edit url.",
        "tags": [
          "Blogs"
        ],
        "security": [
          {
            "Location-Access": [
              "blogs/check-slug.readonly"
            ]
          }
        ]
      }
    },
    "/blogs/posts/{postId}": {
      "put": {
        "operationId": "update-blog-post",
        "summary": "Update Blog Post",
        "description": "The \"Update Blog Post\" API allows you update blog post for any given blog site. Please use blogs/post-update.write",
        "tags": [
          "Blogs"
        ],
        "security": [
          {
            "Location-Access": [
              "blogs/post-update.write"
            ]
          }
        ]
      }
    },
    "/blogs/posts": {
      "post": {
        "operationId": "create-blog-post",
        "summary": "Create Blog Post",
        "description": "The \"Create Blog Post\" API allows you create blog post for any given blog site. Please use blogs/post.write",
        "tags": [
          "Blogs"
        ],
        "security": [
          {
            "Location-Access": [
              "blogs/post.write"
            ]
          }
        ]
      }
    },
    "/blogs/authors": {
      "get": {
        "operationId": "get-all-blog-authors-by-location",
        "summary": "Get all authors",
        "description": "The \"Get all authors\" Api return the blog authors for a given location ID. Please use \"blogs/author.readonly\" ",
        "tags": [
          "Blogs"
        ],
        "security": [
          {
            "Location-Access": [
              "blogs/author.readonly"
            ]
          }
        ]
      }
    },
    "/blogs/categories": {
      "get": {
        "operationId": "get-all-categories-by-location",
        "summary": "Get all categories",
        "description": "The \"Get all categories\" Api return the blog categoies for a given location ID. Please use \"blogs/category.readonly\" ",
        "tags": [
          "Blogs"
        ],
        "security": [
          {
            "Location-Access": [
              "blogs/category.readonly"
            ]
          }
        ]
      }
    },
    "/blogs/posts/all": {
      "get": {
        "operationId": "get-blog-post",
        "summary": "Get Blog posts by Blog ID",
        "description": "The \"Get Blog posts by Blog ID\" API allows you get blog posts for any given blog site using blog ID.Please use blogs/posts.readonly",
        "tags": [
          "Blogs"
        ],
        "security": [
          {
            "Location-Access": [
              "blogs/posts.readonly"
            ]
          }
        ]
      }
    },
    "/blogs/site/all": {
      "get": {
        "operationId": "get-blogs",
        "summary": "Get Blogs by Location ID",
        "description": "The \"Get Blogs by Location ID\" API allows you get blogs using Location ID.Please use blogs/list.readonly",
        "tags": [
          "Blogs"
        ],
        "security": [
          {
            "Location-Access": [
              "blogs/list.readonly"
            ]
          }
        ]
      }
    },
    "/businesses/{businessId}": {
      "put": {
        "operationId": "update-business",
        "summary": "Update Business",
        "description": "Update Business",
        "tags": [
          "Businesses"
        ],
        "security": [
          {
            "bearer": [
              "businesses.write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete-Business",
        "summary": "Delete Business",
        "description": "Delete Business",
        "tags": [
          "Businesses"
        ],
        "security": [
          {
            "bearer": [
              "businesses.write"
            ]
          }
        ]
      },
      "get": {
        "operationId": "get-business",
        "summary": "Get Business",
        "description": "Get Business",
        "tags": [
          "Businesses"
        ],
        "security": [
          {
            "bearer": [
              "businesses.readonly"
            ]
          }
        ]
      }
    },
    "/businesses/": {
      "get": {
        "operationId": "get-businesses-by-location",
        "summary": "Get Businesses by Location",
        "description": "Get Businesses by Location",
        "tags": [
          "Businesses"
        ],
        "security": [
          {
            "bearer": [
              "businesses.readonly"
            ]
          }
        ]
      },
      "post": {
        "operationId": "create-business",
        "summary": "Create Business",
        "description": "Create Business",
        "tags": [
          "Businesses"
        ],
        "security": [
          {
            "bearer": [
              "businesses.write"
            ]
          }
        ]
      }
    },
    "/calendars/groups": {
      "get": {
        "operationId": "get-groups",
        "summary": "Get Groups",
        "description": "Get all calendar groups in a location.",
        "tags": [
          "Calendar Groups"
        ],
        "security": [
          {
            "bearer": [
              "calendars/groups.readonly"
            ]
          }
        ]
      },
      "post": {
        "operationId": "create-calendar-group",
        "summary": "Create Calendar Group",
        "description": "Create Calendar Group",
        "tags": [
          "Calendar Groups"
        ],
        "security": [
          {
            "bearer": [
              "calendars/groups.write"
            ]
          }
        ]
      }
    },
    "/calendars/groups/validate-slug": {
      "post": {
        "operationId": "validate-groups-slug",
        "summary": "Validate group slug",
        "description": "Validate if group slug is available or not.",
        "tags": [
          "Calendar Groups"
        ],
        "security": [
          {
            "bearer": [
              "calendars/groups.write"
            ]
          }
        ]
      }
    },
    "/calendars/groups/{groupId}": {
      "delete": {
        "operationId": "delete-group",
        "summary": "Delete Group",
        "description": "Delete Group",
        "tags": [
          "Calendar Groups"
        ],
        "security": [
          {
            "bearer": [
              "calendars/groups.write"
            ]
          }
        ]
      },
      "put": {
        "operationId": "edit-group",
        "summary": "Update Group",
        "description": "Update Group by group ID",
        "tags": [
          "Calendar Groups"
        ],
        "security": [
          {
            "bearer": [
              "calendars/groups.write"
            ]
          }
        ]
      }
    },
    "/calendars/groups/{groupId}/status": {
      "put": {
        "operationId": "disable-group",
        "summary": "Disable Group",
        "description": "Disable Group",
        "tags": [
          "Calendar Groups"
        ],
        "security": [
          {
            "bearer": [
              "calendars/groups.write"
            ]
          }
        ]
      }
    },
    "/calendars/events/appointments": {
      "post": {
        "operationId": "create-appointment",
        "summary": "Create appointment",
        "description": "Create appointment",
        "tags": [
          "Calendar Events"
        ],
        "security": [
          {
            "bearer": [
              "calendars/events.write"
            ]
          }
        ]
      }
    },
    "/calendars/events/appointments/{eventId}": {
      "put": {
        "operationId": "edit-appointment",
        "summary": "Update Appointment",
        "description": "Update appointment",
        "tags": [
          "Calendar Events"
        ],
        "security": [
          {
            "bearer": [
              "calendars/events.write"
            ]
          }
        ]
      },
      "get": {
        "operationId": "get-appointment",
        "summary": "Get Appointment",
        "description": "Get appointment by ID",
        "tags": [
          "Calendar Events"
        ],
        "security": [
          {
            "bearer": [
              "calendars/events.readonly"
            ]
          }
        ]
      }
    },
    "/calendars/events": {
      "get": {
        "operationId": "get-calendar-events",
        "summary": "Get Calendar Events",
        "description": "Get Calendar Events",
        "tags": [
          "Calendar Events"
        ],
        "security": [
          {
            "bearer": [
              "calendars/events.readonly"
            ]
          }
        ]
      }
    },
    "/calendars/blocked-slots": {
      "get": {
        "operationId": "get-blocked-slots",
        "summary": "Get Blocked Slots",
        "description": "Get Blocked Slots",
        "tags": [
          "Calendar Events"
        ],
        "security": [
          {
            "bearer": [
              "calendars/events.readonly"
            ]
          }
        ]
      }
    },
    "/calendars/events/block-slots": {
      "post": {
        "operationId": "create-block-slot",
        "summary": "Create Block Slot",
        "description": "Create block slot",
        "tags": [
          "Calendar Events"
        ],
        "security": [
          {
            "bearer": [
              "calendars/events.write"
            ]
          }
        ]
      }
    },
    "/calendars/events/block-slots/{eventId}": {
      "put": {
        "operationId": "edit-block-slot",
        "summary": "Update Block Slot",
        "description": "Update block slot by ID",
        "tags": [
          "Calendar Events"
        ],
        "security": [
          {
            "bearer": [
              "calendars/events.write"
            ]
          }
        ]
      }
    },
    "/calendars/{calendarId}/free-slots": {
      "get": {
        "operationId": "get-slots",
        "summary": "Get Free Slots",
        "description": "Get free slots for a calendar between a date range. Optionally a consumer can also request free slots in a particular timezone and also for a particular user.",
        "tags": [
          "Calendars"
        ],
        "security": [
          {
            "bearer": [
              "calendars.readonly"
            ]
          }
        ]
      }
    },
    "/calendars/{calendarId}": {
      "put": {
        "operationId": "update-calendar",
        "summary": "Update Calendar",
        "description": "Update calendar by ID.",
        "tags": [
          "Calendars"
        ],
        "security": [
          {
            "bearer": [
              "calendars.write"
            ]
          }
        ]
      },
      "get": {
        "operationId": "get-calendar",
        "summary": "Get Calendar",
        "description": "Get calendar by ID",
        "tags": [
          "Calendars"
        ],
        "security": [
          {
            "bearer": [
              "calendars.readonly"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete-calendar",
        "summary": "Delete Calendar",
        "description": "Delete calendar by ID",
        "tags": [
          "Calendars"
        ],
        "security": [
          {
            "bearer": [
              "calendars.write"
            ]
          }
        ]
      }
    },
    "/calendars/events/{eventId}": {
      "delete": {
        "operationId": "delete-event",
        "summary": "Delete Event",
        "description": "Delete event by ID",
        "tags": [
          "Calendar Events"
        ],
        "security": [
          {
            "bearer": [
              "calendars/events.write"
            ]
          }
        ]
      }
    },
    "/calendars/appointments/{appointmentId}/notes": {
      "get": {
        "operationId": "get-appointment-notes",
        "summary": "Get Notes",
        "description": "Get Appointment Notes",
        "tags": [
          "Appointment Notes"
        ],
        "security": [
          {
            "bearer": [
              "calendars/events.readonly"
            ]
          }
        ]
      },
      "post": {
        "operationId": "create-appointment-note",
        "summary": "Create Note",
        "description": "Create Note",
        "tags": [
          "Appointment Notes"
        ],
        "security": [
          {
            "bearer": [
              "calendars/events.write"
            ]
          }
        ]
      }
    },
    "/calendars/appointments/{appointmentId}/notes/{noteId}": {
      "put": {
        "operationId": "update-appointment-note",
        "summary": "Update Note",
        "description": "Update Note",
        "tags": [
          "Appointment Notes"
        ],
        "security": [
          {
            "bearer": [
              "calendars/events.write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete-appointment-note",
        "summary": "Delete Note",
        "description": "Delete Note",
        "tags": [
          "Appointment Notes"
        ],
        "security": [
          {
            "bearer": [
              "calendars/events.write"
            ]
          }
        ]
      }
    },
    "/calendars/resources/{resourceType}/{id}": {
      "get": {
        "operationId": "get-calendar-resource",
        "summary": "Get Calendar Resource",
        "description": "Get calendar resource by ID",
        "tags": [
          "Calendar Resources: Rooms & Equipments"
        ],
        "security": [
          {
            "Location-Access": [
              "calendars/resources.readonly"
            ]
          }
        ]
      },
      "put": {
        "operationId": "update-calendar-resource",
        "summary": "Update Calendar Resource",
        "description": "Update calendar resource by ID",
        "tags": [
          "Calendar Resources: Rooms & Equipments"
        ],
        "security": [
          {
            "Location-Access": [
              "calendars/resources.write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete-calendar-resource",
        "summary": "Delete Calendar Resource",
        "description": "Delete calendar resource by ID",
        "tags": [
          "Calendar Resources: Rooms & Equipments"
        ],
        "security": [
          {
            "Location-Access": [
              "calendars/resources.write"
            ]
          }
        ]
      }
    },
    "/calendars/resources/{resourceType}": {
      "get": {
        "operationId": "fetch-calendar-resources",
        "summary": "List Calendar Resources",
        "description": "List calendar resources by resource type and location ID",
        "tags": [
          "Calendar Resources: Rooms & Equipments"
        ],
        "security": [
          {
            "Location-Access": [
              "calendars/resources.readonly"
            ]
          }
        ]
      },
      "post": {
        "operationId": "create-calendar-resource",
        "summary": "Create Calendar Resource",
        "description": "Create calendar resource by resource type",
        "tags": [
          "Calendar Resources: Rooms & Equipments"
        ],
        "security": [
          {
            "Location-Access": [
              "calendars/resources.write"
            ]
          }
        ]
      }
    },
    "/calendars/{calendarId}/notifications": {
      "get": {
        "operationId": "get-event-notification",
        "summary": "Get notifications",
        "description": "Get calendar notifications based on query",
        "tags": [
          "Calendar Notifications"
        ],
        "security": [
          {
            "bearer": [
              "calendars/events.readonly"
            ]
          }
        ]
      },
      "post": {
        "operationId": "create-event-notification",
        "summary": "Create notification",
        "description": "Create Calendar notifications, either one or multiple. All notification settings must be for single calendar only",
        "tags": [
          "Calendar Notifications"
        ],
        "security": [
          {
            "bearer": [
              "calendars/events.write"
            ]
          }
        ]
      }
    },
    "/calendars/{calendarId}/notifications/{notificationId}": {
      "get": {
        "operationId": "find-event-notification",
        "summary": "Get notification",
        "description": "Find Event notification by notificationId",
        "tags": [
          "Calendar Notifications"
        ],
        "security": [
          {
            "bearer": [
              "calendars/events.readonly"
            ]
          }
        ]
      },
      "put": {
        "operationId": "update-event-notification",
        "summary": "Update notification",
        "description": "Update Event notification by id",
        "tags": [
          "Calendar Notifications"
        ],
        "security": [
          {
            "bearer": [
              "calendars/events.write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete-event-notification",
        "summary": "Delete Notification",
        "description": "Delete notification",
        "tags": [
          "Calendar Notifications"
        ],
        "security": [
          {
            "bearer": [
              "calendars/events.write"
            ]
          }
        ]
      }
    },
    "/calendars/": {
      "get": {
        "operationId": "get-calendars",
        "summary": "Get Calendars",
        "description": "Get all calendars in a location.",
        "tags": [
          "Calendars"
        ],
        "security": [
          {
            "bearer": [
              "calendars.readonly"
            ]
          }
        ]
      },
      "post": {
        "operationId": "create-calendar",
        "summary": "Create Calendar",
        "description": "Create calendar in a location.",
        "tags": [
          "Calendars"
        ],
        "security": [
          {
            "bearer": [
              "calendars.write"
            ]
          }
        ]
      }
    },
    "/campaigns/": {
      "get": {
        "operationId": "get-campaigns",
        "summary": "Get Campaigns",
        "description": "Get Campaigns",
        "tags": [
          "Campaigns"
        ],
        "security": [
          {
            "bearer": [
              "campaigns.readonly"
            ]
          }
        ]
      }
    },
    "/companies/{companyId}": {
      "get": {
        "operationId": "get-company",
        "summary": "Get Company",
        "description": "Get Comapny",
        "tags": [
          "Companies"
        ],
        "security": [
          {
            "Agency-Access": [
              "companies.readonly"
            ]
          }
        ]
      }
    },
    "/contacts/search": {
      "post": {
        "operationId": "search-contacts-advanced",
        "summary": "Search Contacts",
        "description": "Search contacts based on combinations of advanced filters. Documentation Link - https://doc.clickup.com/8631005/d/h/87cpx-158396/6e629989abe7fad",
        "tags": [
          "Search"
        ],
        "security": [
          {
            "bearer": [
              "contacts.readonly"
            ]
          }
        ]
      }
    },
    "/contacts/search/duplicate": {
      "get": {
        "operationId": "get-duplicate-contact",
        "summary": "Get Duplicate Contact",
        "description": "Get Duplicate Contact.<br/><br/>If `Allow Duplicate Contact` is disabled under Settings, the global unique identifier will be used for searching the contact. If the setting is enabled, first priority for search is `email` and the second priority will be `phone`.",
        "tags": [
          "Search"
        ],
        "security": [
          {
            "bearer": [
              "contacts.readonly"
            ]
          }
        ]
      }
    },
    "/contacts/{contactId}/tasks": {
      "get": {
        "operationId": "get-all-tasks",
        "summary": "Get all Tasks",
        "description": "Get all Tasks",
        "tags": [
          "Tasks"
        ],
        "security": [
          {
            "bearer": [
              "contacts.readonly"
            ]
          }
        ]
      },
      "post": {
        "operationId": "create-task",
        "summary": "Create Task",
        "description": "Create Task",
        "tags": [
          "Tasks"
        ],
        "security": [
          {
            "bearer": [
              "contacts.write"
            ]
          }
        ]
      }
    },
    "/contacts/{contactId}/tasks/{taskId}": {
      "get": {
        "operationId": "get-task",
        "summary": "Get Task",
        "description": "Get Task",
        "tags": [
          "Tasks"
        ],
        "security": [
          {
            "bearer": [
              "contacts.readonly"
            ]
          }
        ]
      },
      "put": {
        "operationId": "update-task",
        "summary": "Update Task",
        "description": "Update Task",
        "tags": [
          "Tasks"
        ],
        "security": [
          {
            "bearer": [
              "contacts.write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete-task",
        "summary": "Delete Task",
        "description": "Delete Task",
        "tags": [
          "Tasks"
        ],
        "security": [
          {
            "bearer": [
              "contacts.write"
            ]
          }
        ]
      }
    },
    "/contacts/{contactId}/tasks/{taskId}/completed": {
      "put": {
        "operationId": "update-task-completed",
        "summary": "Update Task Completed",
        "description": "Update Task Completed",
        "tags": [
          "Tasks"
        ],
        "security": [
          {
            "bearer": [
              "contacts.write"
            ]
          }
        ]
      }
    },
    "/contacts/{contactId}/appointments": {
      "get": {
        "operationId": "get-appointments-for-contact",
        "summary": "Get Appointments for Contact",
        "description": "Get Appointments for Contact",
        "tags": [
          "Appointments"
        ],
        "security": [
          {
            "bearer": [
              "contacts.readonly"
            ]
          }
        ]
      }
    },
    "/contacts/{contactId}/tags": {
      "post": {
        "operationId": "add-tags",
        "summary": "Add Tags",
        "description": "Add Tags",
        "tags": [
          "Tags"
        ],
        "security": [
          {
            "bearer": [
              "contacts.write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "remove-tags",
        "summary": "Remove Tags",
        "description": "Remove Tags",
        "tags": [
          "Tags"
        ],
        "security": [
          {
            "bearer": [
              "contacts.write"
            ]
          }
        ]
      }
    },
    "/contacts/{contactId}/notes": {
      "get": {
        "operationId": "get-all-notes",
        "summary": "Get All Notes",
        "description": "Get All Notes",
        "tags": [
          "Notes"
        ],
        "security": [
          {
            "bearer": [
              "contacts.readonly"
            ]
          }
        ]
      },
      "post": {
        "operationId": "create-note",
        "summary": "Create Note",
        "description": "Create Note",
        "tags": [
          "Notes"
        ],
        "security": [
          {
            "bearer": [
              "contacts.write"
            ]
          }
        ]
      }
    },
    "/contacts/{contactId}/notes/{id}": {
      "get": {
        "operationId": "get-note",
        "summary": "Get Note",
        "description": "Get Note",
        "tags": [
          "Notes"
        ],
        "security": [
          {
            "bearer": [
              "contacts.readonly"
            ]
          }
        ]
      },
      "put": {
        "operationId": "update-note",
        "summary": "Update Note",
        "description": "Update Note",
        "tags": [
          "Notes"
        ],
        "security": [
          {
            "bearer": [
              "contacts.write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete-note",
        "summary": "Delete Note",
        "description": "Delete Note",
        "tags": [
          "Notes"
        ],
        "security": [
          {
            "bearer": [
              "contacts.write"
            ]
          }
        ]
      }
    },
    "/contacts/bulk/tags/update/{type}": {
      "post": {
        "operationId": "create-association",
        "summary": "Update Contacts Tags",
        "description": "Allows you to update tags to multiple contacts at once, you can add or remove tags from the contacts",
        "tags": [
          "Bulk"
        ]
      }
    },
    "/contacts/bulk/business": {
      "post": {
        "operationId": "add-remove-contact-from-business",
        "summary": "Add/Remove Contacts From Business",
        "description": "Add/Remove Contacts From Business . Passing a `null` businessId will remove the businessId from the contacts",
        "tags": [
          "Bulk"
        ]
      }
    },
    "/contacts/{contactId}": {
      "get": {
        "operationId": "get-contact",
        "summary": "Get Contact",
        "description": "Get Contact",
        "tags": [
          "Contacts"
        ],
        "security": [
          {
            "bearer": [
              "contacts.readonly"
            ]
          }
        ]
      },
      "put": {
        "operationId": "update-contact",
        "summary": "Update Contact",
        "description": "Please find the list of acceptable values for the `country` field  <a href=\"https://highlevel.stoplight.io/docs/integrations/ZG9jOjI4MzUzNDIy-country-list\" target=\"_blank\">here</a>",
        "tags": [
          "Contacts"
        ],
        "security": [
          {
            "bearer": [
              "contacts.write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete-contact",
        "summary": "Delete Contact",
        "description": "Delete Contact",
        "tags": [
          "Contacts"
        ],
        "security": [
          {
            "bearer": [
              "contacts.write"
            ]
          }
        ]
      }
    },
    "/contacts/upsert": {
      "post": {
        "operationId": "upsert-contact",
        "summary": "Upsert Contact",
        "description": "Please find the list of acceptable values for the `country` field  <a href=\"https://highlevel.stoplight.io/docs/integrations/ZG9jOjI4MzUzNDIy-country-list\" target=\"_blank\">here</a><br/><br/>The Upsert API will adhere to the configuration defined under the “Allow Duplicate Contact” setting at the Location level. If the setting is configured to check both Email and Phone, the API will attempt to identify an existing contact based on the priority sequence specified in th[...]",
        "tags": [
          "Contacts"
        ],
        "security": [
          {
            "bearer": [
              "contacts.write"
            ]
          }
        ]
      }
    },
    "/contacts/business/{businessId}": {
      "get": {
        "operationId": "get-contacts-by-businessId",
        "summary": "Get Contacts By BusinessId",
        "description": "Get Contacts By BusinessId",
        "tags": [
          "Contacts"
        ],
        "security": [
          {
            "bearer": [
              "contacts.readonly"
            ]
          }
        ]
      }
    },
    "/contacts/{contactId}/followers": {
      "post": {
        "operationId": "add-followers-contact",
        "summary": "Add Followers",
        "description": "Add Followers",
        "tags": [
          "Followers"
        ],
        "security": [
          {
            "bearer": [
              "contacts.write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "remove-followers-contact",
        "summary": "Remove Followers",
        "description": "Remove Followers",
        "tags": [
          "Followers"
        ],
        "security": [
          {
            "bearer": [
              "contacts.write"
            ]
          }
        ]
      }
    },
    "/contacts/{contactId}/campaigns/{campaignId}": {
      "post": {
        "operationId": "add-contact-to-campaign",
        "summary": "Add Contact to Campaign",
        "description": "Add contact to Campaign",
        "tags": [
          "Campaigns"
        ],
        "security": [
          {
            "bearer": [
              "contacts.write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "remove-contact-from-campaign",
        "summary": "Remove Contact From Campaign",
        "description": "Remove Contact From Campaign",
        "tags": [
          "Campaigns"
        ],
        "security": [
          {
            "bearer": [
              "contacts.write"
            ]
          }
        ]
      }
    },
    "/contacts/{contactId}/campaigns/removeAll": {
      "delete": {
        "operationId": "remove-contact-from-every-campaign",
        "summary": "Remove Contact From Every Campaign",
        "description": "Remove Contact From Every Campaign",
        "tags": [
          "Campaigns"
        ],
        "security": [
          {
            "bearer": [
              "contacts.write"
            ]
          }
        ]
      }
    },
    "/contacts/{contactId}/workflow/{workflowId}": {
      "post": {
        "operationId": "add-contact-to-workflow",
        "summary": "Add Contact to Workflow",
        "description": "Add Contact to Workflow",
        "tags": [
          "Workflow"
        ],
        "security": [
          {
            "bearer": [
              "contacts.write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete-contact-from-workflow",
        "summary": "Delete Contact from Workflow",
        "description": "Delete Contact from Workflow",
        "tags": [
          "Workflow"
        ],
        "security": [
          {
            "bearer": [
              "contacts.write"
            ]
          }
        ]
      }
    },
    "/contacts/": {
      "post": {
        "operationId": "create-contact",
        "summary": "Create Contact",
        "description": "Please find the list of acceptable values for the `country` field  <a href=\"https://highlevel.stoplight.io/docs/integrations/ZG9jOjI4MzUzNDIy-country-list\" target=\"_blank\">here</a>",
        "tags": [
          "Contacts"
        ],
        "security": [
          {
            "bearer": [
              "contacts.write"
            ]
          }
        ]
      },
      "get": {
        "operationId": "get-contacts",
        "summary": "Get Contacts",
        "description": "Get Contacts\n\n **Note:** This API endpoint is deprecated. Please use the [Search Contacts](https://highlevel.stoplight.io/docs/integrations/dbe4f3a00a106-search-contacts) endpoint instead.",
        "deprecated": true,
        "tags": [
          "Contacts"
        ],
        "security": [
          {
            "bearer": [
              "contacts.readonly"
            ]
          }
        ]
      }
    },
    "/conversations/search": {
      "get": {
        "operationId": "search-conversation",
        "summary": "Search Conversations",
        "description": "Returns a list of all conversations matching the search criteria along with the sort and filter options selected.",
        "tags": [
          "Search"
        ],
        "security": [
          {
            "bearer": [
              "conversations.readonly"
            ]
          }
        ]
      }
    },
    "/conversations/{conversationId}": {
      "get": {
        "operationId": "get-conversation",
        "summary": "Get Conversation",
        "description": "Get the conversation details based on the conversation ID",
        "tags": [
          "Conversations"
        ],
        "security": [
          {
            "bearer": [
              "conversations.readonly"
            ]
          }
        ]
      },
      "put": {
        "operationId": "update-conversation",
        "summary": "Update Conversation",
        "description": "Update the conversation details based on the conversation ID",
        "tags": [
          "Conversations"
        ],
        "security": [
          {
            "bearer": [
              "conversations.write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete-conversation",
        "summary": "Delete Conversation",
        "description": "Delete the conversation details based on the conversation ID",
        "tags": [
          "Conversations"
        ],
        "security": [
          {
            "bearer": [
              "conversations.write"
            ]
          }
        ]
      }
    },
    "/conversations/messages/email/{id}": {
      "get": {
        "operationId": "get-email-by-id",
        "summary": "Get email by Id",
        "description": "Get email by Id",
        "tags": [
          "Email"
        ]
      }
    },
    "/conversations/messages/email/{emailMessageId}/schedule": {
      "delete": {
        "operationId": "cancel-scheduled-email-message",
        "summary": "Cancel a scheduled email message.",
        "description": "Post the messageId for the API to delete a scheduled email message. <br />",
        "tags": [
          "Email"
        ]
      }
    },
    "/conversations/messages/{id}": {
      "get": {
        "operationId": "get-message",
        "summary": "Get message by message id",
        "description": "Get message by message id.",
        "tags": [
          "Messages"
        ],
        "security": [
          {
            "bearer": [
              "conversations/message.readonly"
            ]
          }
        ]
      }
    },
    "/conversations/{conversationId}/messages": {
      "get": {
        "operationId": "get-messages",
        "summary": "Get messages by conversation id",
        "description": "Get messages by conversation id.",
        "tags": [
          "Messages"
        ],
        "security": [
          {
            "bearer": [
              "conversations/message.readonly"
            ]
          }
        ]
      }
    },
    "/conversations/messages": {
      "post": {
        "operationId": "send-a-new-message",
        "summary": "Send a new message",
        "description": "Post the necessary fields for the API to send a new message.",
        "tags": [
          "Messages"
        ],
        "security": [
          {
            "bearer": [
              "conversations/message.write"
            ]
          }
        ]
      }
    },
    "/conversations/messages/inbound": {
      "post": {
        "operationId": "add-an-inbound-message",
        "summary": "Add an inbound message",
        "description": "Post the necessary fields for the API to add a new inbound message. <br />",
        "tags": [
          "Messages"
        ],
        "security": [
          {
            "bearer": [
              "conversations/message.write"
            ]
          }
        ]
      }
    },
    "/conversations/messages/outbound": {
      "post": {
        "operationId": "add-an-outbound-message",
        "summary": "Add an external outbound call",
        "description": "Post the necessary fields for the API to add a new outbound call.",
        "tags": [
          "Messages"
        ],
        "security": [
          {
            "bearer": [
              "conversations/message.write"
            ]
          }
        ]
      }
    },
    "/conversations/messages/{messageId}/schedule": {
      "delete": {
        "operationId": "cancel-scheduled-message",
        "summary": "Cancel a scheduled message.",
        "description": "Post the messageId for the API to delete a scheduled message. <br />",
        "tags": [
          "Messages"
        ],
        "security": [
          {
            "bearer": [
              "conversations/message.write"
            ]
          }
        ]
      }
    },
    "/conversations/messages/upload": {
      "post": {
        "operationId": "upload-file-attachments",
        "summary": "Upload file attachments",
        "description": "Post the necessary fields for the API to upload files. The files need to be a buffer with the key \"fileAttachment\". <br /><br /> The allowed file types are: <br/> <ul><li>JPG</li><li>JPEG</li><li>PNG</li><li>MP4</li><li>MPEG</li><li>ZIP</li><li>RAR</li><li>PDF</li><li>DOC</li><li>DOCX</li><li>TXT</li><li>MP3</li><li>WAV</li></ul> <br /><br /> The API will return an object with the URLs",
        "tags": [
          "Messages"
        ],
        "security": [
          {
            "bearer": [
              "conversations/message.write"
            ]
          }
        ]
      }
    },
    "/conversations/messages/{messageId}/status": {
      "put": {
        "operationId": "update-message-status",
        "summary": "Update message status",
        "description": "Post the necessary fields for the API to update message status.",
        "tags": [
          "Messages"
        ],
        "security": [
          {
            "bearer": [
              "conversations/message.write"
            ]
          }
        ]
      }
    },
    "/conversations/messages/{messageId}/locations/{locationId}/recording": {
      "get": {
        "operationId": "get-message-recording",
        "summary": "Get Recording by Message ID",
        "description": "Get the recording for a message by passing the message id",
        "tags": [
          "Messages"
        ],
        "security": [
          {
            "bearer": []
          },
          {
            "Location-Access": []
          }
        ]
      }
    },
    "/conversations/locations/{locationId}/messages/{messageId}/transcription": {
      "get": {
        "operationId": "get-message-transcription",
        "summary": "Get transcription by Message ID",
        "description": "Get the recording transcription for a message by passing the message id",
        "tags": [
          "Messages"
        ],
        "security": [
          {
            "bearer": []
          },
          {
            "Location-Access": []
          }
        ]
      }
    },
    "/conversations/locations/{locationId}/messages/{messageId}/transcription/download": {
      "get": {
        "operationId": "download-message-transcription",
        "summary": "Download transcription by Message ID",
        "description": "Download the recording transcription for a message by passing the message id",
        "tags": [
          "Messages"
        ],
        "security": [
          {
            "bearer": []
          },
          {
            "Location-Access": []
          }
        ]
      }
    },
    "/conversations/providers/live-chat/typing": {
      "post": {
        "operationId": "live-chat-agent-typing",
        "summary": "Agent/Ai-Bot is typing a message indicator for live chat",
        "description": "Agent/AI-Bot will call this when they are typing a message in live chat message",
        "tags": [
          "Providers"
        ],
        "security": [
          {
            "Location-Access": [
              "conversations/livechat.write"
            ]
          }
        ]
      }
    },
    "/conversations/": {
      "post": {
        "operationId": "create-conversation",
        "summary": "Create Conversation",
        "description": "Creates a new conversation with the data provided",
        "tags": [
          "Conversations"
        ],
        "security": [
          {
            "bearer": [
              "conversations.write"
            ]
          }
        ]
      }
    },
    "/courses/courses-exporter/public/import": {
      "post": {
        "operationId": "import-courses",
        "summary": "Import Courses",
        "description": "Import Courses through public channels",
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/custom-fields/{id}": {
      "get": {
        "operationId": "get-custom-field-by-id",
        "summary": "Get Custom Field / Folder By Id",
        "description": "<div>\n                  <p> Get Custom Field / Folder By Id.</p> \n                  <div>\n                    <span style= \"display: inline-block;\n                                width: 25px; height: 25px;\n                                background-color: yellow;\n                                color: black;\n                                font-weight: bold;\n                                font-size: 24px;\n                                text-align: center;\n   [...]",
        "tags": [
          "Custom Fields V2"
        ],
        "security": [
          {
            "bearer": [
              "locations/customFields.readonly"
            ]
          }
        ]
      },
      "put": {
        "operationId": "update-custom-field",
        "summary": "Update Custom Field By Id",
        "description": "<div>\n    <p> Update Custom Field By Id </p> \n    <div>\n      <span style= \"display: inline-block;\n                  width: 25px; height: 25px;\n                  background-color: yellow;\n                  color: black;\n                  font-weight: bold;\n                  font-size: 24px;\n                  text-align: center;\n                  line-height: 22px;\n                  border: 2px solid black;\n                  border-radius: 10%;\n              [...]",
        "tags": [
          "Custom Fields V2"
        ],
        "security": [
          {
            "bearer": [
              "locations/customFields.write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete-custom-field",
        "summary": "Delete Custom Field By Id",
        "description": "<div>\n    <p> Delete Custom Field By Id </p> \n    <div>\n      <span style= \"display: inline-block;\n                  width: 25px; height: 25px;\n                  background-color: yellow;\n                  color: black;\n                  font-weight: bold;\n                  font-size: 24px;\n                  text-align: center;\n                  line-height: 22px;\n                  border: 2px solid black;\n                  border-radius: 10%;\n              [...]",
        "tags": [
          "Custom Fields V2"
        ],
        "security": [
          {
            "bearer": [
              "locations/customFields.write"
            ]
          }
        ]
      }
    },
    "/custom-fields/object-key/{objectKey}": {
      "get": {
        "operationId": "get-custom-fields-by-object-key",
        "summary": "Get Custom Fields By Object Key",
        "description": "<div>\n                  <p> Get Custom Fields By Object Key</p> \n                  <div>\n                    <span style= \"display: inline-block;\n                                width: 25px; height: 25px;\n                                background-color: yellow;\n                                color: black;\n                                font-weight: bold;\n                                font-size: 24px;\n                                text-align: center;\n    [...]",
        "tags": [
          "Custom Fields V2"
        ],
        "security": [
          {
            "bearer": [
              "locations/customFields.readonly"
            ]
          }
        ]
      }
    },
    "/custom-fields/folder": {
      "post": {
        "operationId": "create-custom-field-folder",
        "summary": "Create Custom Field Folder",
        "description": "<div>\n    <p> Create Custom Field Folder </p> \n    <div>\n      <span style= \"display: inline-block;\n                  width: 25px; height: 25px;\n                  background-color: yellow;\n                  color: black;\n                  font-weight: bold;\n                  font-size: 24px;\n                  text-align: center;\n                  line-height: 22px;\n                  border: 2px solid black;\n                  border-radius: 10%;\n             [...]",
        "tags": [
          "Custom Fields V2"
        ],
        "security": [
          {
            "bearer": [
              "locations/customFields.write"
            ]
          }
        ]
      }
    },
    "/custom-fields/folder/{id}": {
      "put": {
        "operationId": "update-custom-field-folder",
        "summary": "Update Custom Field Folder Name",
        "description": "<div>\n    <p> Create Custom Field Folder </p> \n    <div>\n      <span style= \"display: inline-block;\n                  width: 25px; height: 25px;\n                  background-color: yellow;\n                  color: black;\n                  font-weight: bold;\n                  font-size: 24px;\n                  text-align: center;\n                  line-height: 22px;\n                  border: 2px solid black;\n                  border-radius: 10%;\n             [...]",
        "tags": [
          "Custom Fields V2"
        ],
        "security": [
          {
            "bearer": [
              "locations/customFields.write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete-custom-field-folder",
        "summary": "Delete Custom Field Folder",
        "description": "<div>\n    <p> Create Custom Field Folder </p> \n    <div>\n      <span style= \"display: inline-block;\n                  width: 25px; height: 25px;\n                  background-color: yellow;\n                  color: black;\n                  font-weight: bold;\n                  font-size: 24px;\n                  text-align: center;\n                  line-height: 22px;\n                  border: 2px solid black;\n                  border-radius: 10%;\n             [...]",
        "tags": [
          "Custom Fields V2"
        ],
        "security": [
          {
            "bearer": [
              "locations/customFields.write"
            ]
          }
        ]
      }
    },
    "/custom-fields/": {
      "post": {
        "operationId": "create-custom-field",
        "summary": "Create Custom Field",
        "description": "<div>\n                  <p> Create Custom Field </p> \n                  <div>\n                    <span style= \"display: inline-block;\n                                width: 25px; height: 25px;\n                                background-color: yellow;\n                                color: black;\n                                font-weight: bold;\n                                font-size: 24px;\n                                text-align: center;\n               [...]",
        "tags": [
          "Custom Fields V2"
        ],
        "security": [
          {
            "bearer": [
              "locations/customFields.write"
            ]
          }
        ]
      }
    },
    "/custom-menus/{customMenuId}": {
      "get": {
        "operationId": "get-custom-menu-by-id",
        "summary": "Get Custom Menu Link",
        "description": "Fetches a single custom menus based on id. This endpoint allows clients to retrieve custom menu configurations, which may include menu items, categories, and associated metadata",
        "tags": [
          "Custom Menu Links"
        ],
        "security": [
          {
            "Agency-Access": [
              "custom-menu-link.readonly"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete-custom-menu",
        "summary": "Delete Custom Menu Link",
        "description": "Removes a specific custom menu from the system. This operation requires authentication and proper permissions. The custom menu is identified by its unique ID, and the operation is performed within the context of a specific company.",
        "tags": [
          "Custom Menu Links"
        ],
        "security": [
          {
            "Agency-Access": [
              "custom-menu-link.write"
            ]
          }
        ]
      },
      "put": {
        "operationId": "update-custom-menu",
        "summary": "Update Custom Menu Link",
        "description": "Updates an existing custom menu for a given company. Requires authentication and proper permissions.",
        "tags": [
          "Custom Menu Links"
        ],
        "security": [
          {
            "Agency-Access": [
              "custom-menu-link.write"
            ]
          }
        ]
      }
    },
    "/custom-menus/": {
      "get": {
        "operationId": "get-custom-menus",
        "summary": "Get Custom Menu Links",
        "description": "Fetches a collection of custom menus based on specified criteria. This endpoint allows clients to retrieve custom menu configurations, which may include menu items, categories, and associated metadata. The response can be tailored using query parameters for filtering, sorting, and pagination.",
        "tags": [
          "Custom Menu Links"
        ],
        "security": [
          {
            "Agency-Access": [
              "custom-menu-link.readonly"
            ]
          }
        ]
      },
      "post": {
        "operationId": "create-custom-menu",
        "summary": "Create Custom Menu Link",
        "description": "Creates a new custom menu for a company. Requires authentication and proper permissions. For Icon Usage Details please refer to  https://doc.clickup.com/8631005/d/h/87cpx-243696/d60fa70db6b92b2",
        "tags": [
          "Custom Menu Links"
        ],
        "security": [
          {
            "Agency-Access": [
              "custom-menu-link.write"
            ]
          }
        ]
      }
    },
    "/email/verify": {
      "post": {
        "operationId": "verify-email",
        "summary": "Email Verification",
        "description": "Verify Email",
        "tags": [
          "Email Verification"
        ],
        "security": [
          {
            "Location-Access": []
          }
        ]
      }
    },
    "/emails/schedule": {
      "get": {
        "operationId": "fetch-campaigns",
        "summary": "Get Campaigns",
        "description": "Get Campaigns",
        "security": [
          {
            "Location-Access": [
              "emails/schedule.readonly"
            ]
          }
        ],
        "tags": [
          "Campaigns"
        ]
      }
    },
    "/emails/builder": {
      "post": {
        "operationId": "create-template",
        "summary": "Create a new template",
        "description": "Create a new template",
        "security": [
          {
            "Location-Access": [
              "emails/builder.write"
            ]
          }
        ],
        "tags": [
          "Templates"
        ]
      },
      "get": {
        "operationId": "fetch-template",
        "summary": "Fetch email templates",
        "description": "Fetch email templates by location id",
        "security": [
          {
            "Location-Access": [
              "emails/builder.readonly"
            ]
          }
        ],
        "tags": [
          "Templates"
        ]
      }
    },
    "/emails/builder/{locationId}/{templateId}": {
      "delete": {
        "operationId": "delete-template",
        "summary": "Delete a template",
        "description": "Delete a template",
        "security": [
          {
            "Location-Access": []
          }
        ],
        "tags": [
          "Templates"
        ]
      }
    },
    "/emails/builder/data": {
      "post": {
        "operationId": "update-template",
        "summary": "Update a template",
        "description": "Update a template",
        "security": [
          {
            "Location-Access": [
              "emails/builder.write"
            ]
          }
        ],
        "tags": [
          "Templates"
        ]
      }
    },
    "/forms/submissions": {
      "get": {
        "operationId": "get-forms-submissions",
        "summary": "Get Forms Submissions",
        "description": "Get Forms Submissions",
        "tags": [
          "Forms"
        ],
        "security": [
          {
            "bearer": [
              "forms.readonly"
            ]
          }
        ]
      }
    },
    "/forms/upload-custom-files": {
      "post": {
        "operationId": "upload-to-custom-fields",
        "summary": "Upload files to custom fields",
        "description": "Post the necessary fields for the API to upload files. The files need to be a buffer with the key \"< custom_field_id >_< file_id >\". <br /> Here custom field id is the ID of your custom field and file id is a randomly generated id (or uuid) <br /> There is support for multiple file uploads as well. Have multiple fields in the format mentioned.<br />File size is limited to 50 MB.<br /><br /> The allowed file types are: <br/> <ul><li>PDF</li><li>DOCX</li><li>DOC</li><li>J[...]",
        "tags": [
          "Forms"
        ],
        "security": [
          {
            "bearer": [
              "forms.write"
            ]
          },
          {
            "Location-Access": [
              "forms.write"
            ]
          }
        ]
      }
    },
    "/forms/": {
      "get": {
        "operationId": "get-forms",
        "summary": "Get Forms",
        "description": "Get Forms",
        "tags": [
          "Forms"
        ],
        "security": [
          {
            "bearer": [
              "forms.readonly"
            ]
          }
        ]
      }
    },
    "/funnels/lookup/redirect": {
      "post": {
        "operationId": "create-redirect",
        "summary": "Create Redirect",
        "description": "The \"Create Redirect\" API Allows adding a new url redirect to the system. Use this endpoint to create a url redirect with the specified details. Ensure that the required information is provided in the request payload.",
        "tags": [
          "Redirect"
        ],
        "security": [
          {
            "Location-Access": [
              "funnels/redirect.write"
            ]
          }
        ]
      }
    },
    "/funnels/lookup/redirect/{id}": {
      "patch": {
        "operationId": "update-redirect-by-id",
        "summary": "Update Redirect By Id",
        "description": "The \"Update Redirect By Id\" API Allows updating an existing URL redirect in the system. Use this endpoint to modify a URL redirect with the specified ID using details provided in the request payload.",
        "tags": [
          "Redirect"
        ],
        "security": [
          {
            "Location-Access": [
              "funnels/redirect.write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete-redirect-by-id",
        "summary": "Delete Redirect By Id",
        "description": "The \"Delete Redirect By Id\" API Allows deletion of a URL redirect from the system using its unique identifier. Use this endpoint to delete a URL redirect with the specified ID using details provided in the request payload.",
        "tags": [
          "Redirect"
        ],
        "security": [
          {
            "Location-Access": [
              "funnels/redirect.write"
            ]
          }
        ]
      }
    },
    "/funnels/lookup/redirect/list": {
      "get": {
        "operationId": "fetch-redirects-list",
        "summary": "Fetch List of Redirects",
        "description": "Retrieves a list of all URL redirects based on the given query parameters.",
        "tags": [
          "Redirect"
        ],
        "security": [
          {
            "Location-Access": [
              "funnels/redirect.readonly"
            ]
          }
        ]
      }
    },
    "/funnels/funnel/list": {
      "get": {
        "operationId": "getFunnels",
        "summary": "Fetch List of Funnels",
        "description": "Retrieves a list of all funnels based on the given query parameters.",
        "tags": [
          "Funnel"
        ],
        "security": [
          {
            "Location-Access": []
          }
        ]
      }
    },
    "/funnels/page": {
      "get": {
        "operationId": "getPagesByFunnelId",
        "summary": "Fetch list of funnel pages",
        "description": "Retrieves a list of all funnel pages based on the given query parameters.",
        "tags": [
          "Funnel"
        ],
        "security": [
          {
            "Location-Access": []
          }
        ]
      }
    },
    "/funnels/page/count": {
      "get": {
        "operationId": "getPagesCountByFunnelId",
        "summary": "Fetch count of funnel pages",
        "description": "Retrieves count of all funnel pages based on the given query parameters.",
        "tags": [
          "Funnel"
        ],
        "security": [
          {
            "Location-Access": []
          }
        ]
      }
    },
    "/invoices/template": {
      "post": {
        "operationId": "create-invoice-template",
        "summary": "Create template",
        "description": "API to create a template",
        "tags": [
          "Template"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices/template.write"
            ]
          },
          {
            "Agency-Access": [
              "invoices/template.write"
            ]
          }
        ]
      },
      "get": {
        "operationId": "list-invoice-templates",
        "summary": "List templates",
        "description": "API to get list of templates",
        "tags": [
          "Template"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices/template.readonly"
            ]
          },
          {
            "Agency-Access": [
              "invoices/template.readonly"
            ]
          }
        ]
      }
    },
    "/invoices/template/{templateId}": {
      "get": {
        "operationId": "get-invoice-template",
        "summary": "Get an template",
        "description": "API to get an template by template id",
        "tags": [
          "Template"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices/template.readonly"
            ]
          },
          {
            "Agency-Access": [
              "invoices/template.readonly"
            ]
          }
        ]
      },
      "put": {
        "operationId": "update-invoice-template",
        "summary": "Update template",
        "description": "API to update an template by template id",
        "tags": [
          "Template"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices/template.write"
            ]
          },
          {
            "Agency-Access": [
              "invoices/template.write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete-invoice-template",
        "summary": "Delete template",
        "description": "API to update an template by template id",
        "tags": [
          "Template"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices/template.write"
            ]
          },
          {
            "Agency-Access": [
              "invoices/template.write"
            ]
          }
        ]
      }
    },
    "/invoices/template/{templateId}/late-fees-configuration": {
      "patch": {
        "operationId": "update-invoice-template-late-fees-configuration",
        "summary": "Update template late fees configuration",
        "description": "API to update template late fees configuration by template id",
        "tags": [
          "Template"
        ],
        "security": [
          {
            "Location-Access": []
          },
          {
            "Agency-Access": []
          }
        ]
      }
    },
    "/invoices/template/{templateId}/payment-methods-configuration": {
      "patch": {
        "operationId": "update-invoice-payment-methods-configuration",
        "summary": "Update template late fees configuration",
        "description": "API to update template late fees configuration by template id",
        "tags": [
          "Template"
        ],
        "security": [
          {
            "Location-Access": []
          },
          {
            "Agency-Access": []
          }
        ]
      }
    },
    "/invoices/schedule": {
      "post": {
        "operationId": "create-invoice-schedule",
        "summary": "Create Invoice Schedule",
        "description": "API to create an invoice Schedule",
        "tags": [
          "Schedule"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices/schedule.write"
            ]
          },
          {
            "Agency-Access": [
              "invoices/schedule.write"
            ]
          }
        ]
      },
      "get": {
        "operationId": "list-invoice-schedules",
        "summary": "List schedules",
        "description": "API to get list of schedules",
        "tags": [
          "Schedule"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices/schedule.readonly"
            ]
          },
          {
            "Agency-Access": [
              "invoices/schedule.readonly"
            ]
          }
        ]
      }
    },
    "/invoices/schedule/{scheduleId}": {
      "get": {
        "operationId": "get-invoice-schedule",
        "summary": "Get an schedule",
        "description": "API to get an schedule by schedule id",
        "tags": [
          "Schedule"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices/schedule.readonly"
            ]
          },
          {
            "Agency-Access": [
              "invoices/schedule.readonly"
            ]
          }
        ]
      },
      "put": {
        "operationId": "update-invoice-schedule",
        "summary": "Update schedule",
        "description": "API to update an schedule by schedule id",
        "tags": [
          "Schedule"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices/schedule.write"
            ]
          },
          {
            "Agency-Access": [
              "invoices/schedule.write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete-invoice-schedule",
        "summary": "Delete schedule",
        "description": "API to delete an schedule by schedule id",
        "tags": [
          "Schedule"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices/schedule.write"
            ]
          },
          {
            "Agency-Access": [
              "invoices/schedule.write"
            ]
          }
        ]
      }
    },
    "/invoices/schedule/{scheduleId}/updateAndSchedule": {
      "post": {
        "operationId": "update-and-schedule-invoice-schedule",
        "summary": "Update scheduled recurring invoice",
        "description": "API to update scheduled recurring invoice",
        "tags": [
          "Schedule"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices/schedule.write"
            ]
          },
          {
            "Agency-Access": [
              "invoices/schedule.write"
            ]
          }
        ]
      }
    },
    "/invoices/schedule/{scheduleId}/schedule": {
      "post": {
        "operationId": "schedule-invoice-schedule",
        "summary": "Schedule an schedule invoice",
        "description": "API to schedule an schedule invoice to start sending to the customer",
        "tags": [
          "Schedule"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices/schedule.write"
            ]
          },
          {
            "Agency-Access": [
              "invoices/schedule.write"
            ]
          }
        ]
      }
    },
    "/invoices/schedule/{scheduleId}/auto-payment": {
      "post": {
        "operationId": "auto-payment-invoice-schedule",
        "summary": "Manage Auto payment for an schedule invoice",
        "description": "API to manage auto payment for a schedule",
        "tags": [
          "Schedule"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices/schedule.write"
            ]
          },
          {
            "Agency-Access": [
              "invoices/schedule.write"
            ]
          }
        ]
      }
    },
    "/invoices/schedule/{scheduleId}/cancel": {
      "post": {
        "operationId": "cancel-invoice-schedule",
        "summary": "Cancel an scheduled invoice",
        "description": "API to cancel a scheduled invoice by schedule id",
        "tags": [
          "Schedule"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices/schedule.write"
            ]
          },
          {
            "Agency-Access": [
              "invoices/schedule.write"
            ]
          }
        ]
      }
    },
    "/invoices/text2pay": {
      "post": {
        "operationId": "text2pay-invoice",
        "summary": "Create & Send",
        "description": "API to create or update a text2pay invoice",
        "tags": [
          "Text2Pay"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices.write"
            ]
          }
        ]
      }
    },
    "/invoices/generate-invoice-number": {
      "get": {
        "operationId": "generate-invoice-number",
        "summary": "Generate Invoice Number",
        "description": "Get the next invoice number for the given location",
        "tags": [
          "Invoice"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices.readonly"
            ]
          },
          {
            "Agency-Access": [
              "invoices.readonly"
            ]
          }
        ]
      }
    },
    "/invoices/{invoiceId}": {
      "get": {
        "operationId": "get-invoice",
        "summary": "Get invoice",
        "description": "API to get invoice by invoice id",
        "tags": [
          "Invoice"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices.readonly"
            ]
          },
          {
            "Agency-Access": [
              "invoices.readonly"
            ]
          }
        ]
      },
      "put": {
        "operationId": "update-invoice",
        "summary": "Update invoice",
        "description": "API to update invoice by invoice id",
        "tags": [
          "Invoice"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices.write"
            ]
          },
          {
            "Agency-Access": [
              "invoices.write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete-invoice",
        "summary": "Delete invoice",
        "description": "API to delete invoice by invoice id",
        "tags": [
          "Invoice"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices.write"
            ]
          },
          {
            "Agency-Access": [
              "invoices.write"
            ]
          }
        ]
      }
    },
    "/invoices/{invoiceId}/late-fees-configuration": {
      "patch": {
        "operationId": "update-invoice-late-fees-configuration",
        "summary": "Update invoice late fees configuration",
        "description": "API to update invoice late fees configuration by invoice id",
        "tags": [
          "Invoice"
        ],
        "security": [
          {
            "Location-Access": []
          },
          {
            "Agency-Access": []
          }
        ]
      }
    },
    "/invoices/{invoiceId}/void": {
      "post": {
        "operationId": "void-invoice",
        "summary": "Void invoice",
        "description": "API to delete invoice by invoice id",
        "tags": [
          "Invoice"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices.write"
            ]
          },
          {
            "Agency-Access": [
              "invoices.write"
            ]
          }
        ]
      }
    },
    "/invoices/{invoiceId}/send": {
      "post": {
        "operationId": "send-invoice",
        "summary": "Send invoice",
        "description": "API to send invoice by invoice id",
        "tags": [
          "Invoice"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices.write"
            ]
          },
          {
            "Agency-Access": [
              "invoices.write"
            ]
          }
        ]
      }
    },
    "/invoices/{invoiceId}/record-payment": {
      "post": {
        "operationId": "record-invoice",
        "summary": "Record a manual payment for an invoice",
        "description": "API to record manual payment for an invoice by invoice id",
        "tags": [
          "Invoice"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices.write"
            ]
          },
          {
            "Agency-Access": [
              "invoices.write"
            ]
          }
        ]
      }
    },
    "/invoices/stats/last-visited-at": {
      "patch": {
        "operationId": "update-invoice-last-visited-at",
        "summary": "Update invoice last visited at",
        "description": "API to update invoice last visited at by invoice id",
        "tags": [
          "Invoice"
        ],
        "security": [
          {
            "Location-Access": []
          },
          {
            "Agency-Access": []
          }
        ]
      }
    },
    "/invoices/estimate": {
      "post": {
        "operationId": "create-new-estimate",
        "summary": "Create New Estimate",
        "description": "Create a new estimate with the provided details",
        "tags": [
          "Estimate"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices/estimate.write"
            ]
          },
          {
            "Agency-Access": [
              "invoices/estimate.write"
            ]
          }
        ]
      }
    },
    "/invoices/estimate/{estimateId}": {
      "put": {
        "operationId": "update-estimate",
        "summary": "Update Estimate",
        "description": "Update an existing estimate with new details",
        "tags": [
          "Estimate"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices/estimate.write"
            ]
          },
          {
            "Agency-Access": [
              "invoices/estimate.write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete-estimate",
        "summary": "Delete Estimate",
        "description": "Delete an existing estimate",
        "tags": [
          "Estimate"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices/estimate.write"
            ]
          },
          {
            "Agency-Access": [
              "invoices/estimate.write"
            ]
          }
        ]
      }
    },
    "/invoices/estimate/number/generate": {
      "get": {
        "operationId": "generate-estimate-number",
        "summary": "Generate Estimate Number",
        "description": "Get the next estimate number for the given location",
        "tags": [
          "Estimate"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices/estimate.readonly"
            ]
          },
          {
            "Agency-Access": [
              "invoices/estimate.readonly"
            ]
          }
        ]
      }
    },
    "/invoices/estimate/{estimateId}/send": {
      "post": {
        "operationId": "send-estimate",
        "summary": "Send Estimate",
        "description": "API to send estimate by estimate id",
        "tags": [
          "Estimate"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices/estimate.write"
            ]
          },
          {
            "Agency-Access": [
              "invoices/estimate.write"
            ]
          }
        ]
      }
    },
    "/invoices/estimate/{estimateId}/invoice": {
      "post": {
        "operationId": "create-invoice-from-estimate",
        "summary": "Create Invoice from Estimate",
        "description": "Create a new invoice from an existing estimate",
        "tags": [
          "Estimate"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices/estimate.write"
            ]
          },
          {
            "Agency-Access": [
              "invoices/estimate.write"
            ]
          }
        ]
      }
    },
    "/invoices/estimate/list": {
      "get": {
        "operationId": "list-estimates",
        "summary": "List Estimates",
        "description": "Get a paginated list of estimates",
        "tags": [
          "Estimate"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices/estimate.readonly"
            ]
          },
          {
            "Agency-Access": [
              "invoices/estimate.readonly"
            ]
          }
        ]
      }
    },
    "/invoices/estimate/stats/last-visited-at": {
      "patch": {
        "operationId": "update-estimate-last-visited-at",
        "summary": "Update estimate last visited at",
        "description": "API to update estimate last visited at by estimate id",
        "tags": [
          "Estimate"
        ],
        "security": [
          {
            "Location-Access": []
          },
          {
            "Agency-Access": []
          }
        ]
      }
    },
    "/invoices/estimate/template": {
      "get": {
        "operationId": "list-estimate-templates",
        "summary": "List Estimate Templates",
        "description": "Get a list of estimate templates or a specific template by ID",
        "tags": [
          "Estimate"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices/estimate.readonly"
            ]
          },
          {
            "Agency-Access": [
              "invoices/estimate.readonly"
            ]
          }
        ]
      },
      "post": {
        "operationId": "create-estimate-template",
        "summary": "Create Estimate Template",
        "description": "Create a new estimate template",
        "tags": [
          "Estimate"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices/estimate.write"
            ]
          },
          {
            "Agency-Access": [
              "invoices/estimate.write"
            ]
          }
        ]
      }
    },
    "/invoices/estimate/template/{templateId}": {
      "put": {
        "operationId": "update-estimate-template",
        "summary": "Update Estimate Template",
        "description": "Update an existing estimate template",
        "tags": [
          "Estimate"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices/estimate.write"
            ]
          },
          {
            "Agency-Access": [
              "invoices/estimate.write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete-estimate-template",
        "summary": "Delete Estimate Template",
        "description": "Delete an existing estimate template",
        "tags": [
          "Estimate"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices/estimate.write"
            ]
          },
          {
            "Agency-Access": [
              "invoices/estimate.write"
            ]
          }
        ]
      }
    },
    "/invoices/estimate/template/preview": {
      "get": {
        "operationId": "preview-estimate-template",
        "summary": "Preview Estimate Template",
        "description": "Get a preview of an estimate template",
        "tags": [
          "Estimate"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices/estimate.readonly"
            ]
          },
          {
            "Agency-Access": [
              "invoices/estimate.readonly"
            ]
          }
        ]
      }
    },
    "/invoices/": {
      "post": {
        "operationId": "create-invoice",
        "summary": "Create Invoice",
        "description": "API to create an invoice",
        "tags": [
          "Invoice"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices.write"
            ]
          },
          {
            "Agency-Access": [
              "invoices.write"
            ]
          }
        ]
      },
      "get": {
        "operationId": "list-invoices",
        "summary": "List invoices",
        "description": "API to get list of invoices",
        "tags": [
          "Invoice"
        ],
        "security": [
          {
            "Location-Access": [
              "invoices.readonly"
            ]
          },
          {
            "Agency-Access": [
              "invoices.readonly"
            ]
          }
        ]
      }
    },
    "/links/id/{linkId}": {
      "get": {
        "operationId": "get-link-by-id",
        "summary": "Get Link by ID",
        "description": "Get a single link by its ID",
        "tags": [
          "Trigger Links"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/links/{linkId}": {
      "put": {
        "operationId": "update-link",
        "summary": "Update Link",
        "description": "Update Link",
        "tags": [
          "Trigger Links"
        ],
        "security": [
          {
            "bearer": [
              "links.write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete-link",
        "summary": "Delete Link",
        "description": "Delete Link",
        "tags": [
          "Trigger Links"
        ],
        "security": [
          {
            "bearer": [
              "links.write"
            ]
          }
        ]
      }
    },
    "/links/search": {
      "get": {
        "operationId": "search-trigger-links",
        "summary": "Search Trigger Links",
        "description": "Get list of links by searching",
        "tags": [
          "Trigger Links Search"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/links/": {
      "get": {
        "operationId": "get-links",
        "summary": "Get Links",
        "description": "Get Links",
        "tags": [
          "Trigger Links"
        ],
        "security": [
          {
            "bearer": [
              "links.readonly"
            ]
          }
        ]
      },
      "post": {
        "operationId": "create-link",
        "summary": "Create Link",
        "description": "Create Link",
        "tags": [
          "Trigger Links"
        ],
        "security": [
          {
            "bearer": [
              "links.write"
            ]
          }
        ]
      }
    },
    "/locations/search": {
      "get": {
        "operationId": "search-locations",
        "summary": "Search",
        "description": "Search Sub-Account (Formerly Location)",
        "tags": [
          "Search"
        ],
        "security": [
          {
            "Agency-Access": [
              "locations.readonly"
            ]
          },
          {
            "Location-Access": [
              "locations.readonly"
            ]
          }
        ]
      }
    },
    "/locations/{locationId}": {
      "get": {
        "operationId": "get-location",
        "summary": "Get Sub-Account (Formerly Location)",
        "description": "Get details of a Sub-Account (Formerly Location) by passing the sub-account id",
        "tags": [
          "Sub-Account (Formerly Location)"
        ],
        "security": [
          {
            "Location-Access": [
              "locations.readonly"
            ]
          },
          {
            "Agency-Access": [
              "locations.readonly"
            ]
          }
        ]
      },
      "put": {
        "operationId": "put-location",
        "summary": "Put Sub-Account (Formerly Location)",
        "description": "Update a Sub-Account (Formerly Location) based on the data provided",
        "tags": [
          "Sub-Account (Formerly Location)"
        ],
        "security": [
          {
            "Agency-Access": [
              "locations.write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete-location",
        "summary": "Delete Sub-Account (Formerly Location)",
        "description": "Delete a Sub-Account (Formerly Location) from the Agency",
        "tags": [
          "Sub-Account (Formerly Location)"
        ],
        "security": [
          {
            "Agency-Access": [
              "locations.internal-access-only"
            ]
          }
        ]
      }
    },
    "/locations/{locationId}/tags": {
      "get": {
        "operationId": "get-location-tags",
        "summary": "Get Tags",
        "description": "Get Sub-Account (Formerly Location) Tags",
        "tags": [
          "Tags"
        ],
        "security": [
          {
            "bearer": [
              "locations/tags.readonly"
            ]
          }
        ]
      },
      "post": {
        "operationId": "create-tag",
        "summary": "Create Tag",
        "description": "Create tag",
        "tags": [
          "Tags"
        ],
        "security": [
          {
            "bearer": [
              "locations/tags.write"
            ]
          }
        ]
      }
    },
    "/locations/{locationId}/tags/{tagId}": {
      "get": {
        "operationId": "get-tag-by-id",
        "summary": "Get tag by id",
        "description": "Get tag by id",
        "tags": [
          "Tags"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "put": {
        "operationId": "update-tag",
        "summary": "Update tag",
        "description": "Update tag",
        "tags": [
          "Tags"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "delete": {
        "operationId": "delete-tag",
        "summary": "Delete tag",
        "description": "Delete tag",
        "tags": [
          "Tags"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/locations/{locationId}/tasks/search": {
      "post": {
        "operationId": "task-search",
        "summary": "Task Search Filter",
        "description": "Task Search",
        "tags": [
          "Tasks Search"
        ],
        "security": [
          {
            "bearer": [
              "locations/tasks.readonly"
            ]
          }
        ]
      }
    },
    "/locations/{locationId}/recurring-tasks/{id}": {
      "get": {
        "operationId": "get-recurring-task-by-id",
        "summary": "Get Recurring Task By Id",
        "description": "Get Recurring Task By Id",
        "tags": [
          "Recurring Tasks"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "put": {
        "operationId": "update-recurring-task",
        "summary": "Update Recurring Task",
        "description": "Update Recurring Task",
        "tags": [
          "Recurring Tasks"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "delete": {
        "operationId": "delete-recurring-task",
        "summary": "Delete Recurring Task",
        "description": "Delete Recurring Task",
        "tags": [
          "Recurring Tasks"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/locations/{locationId}/recurring-tasks": {
      "post": {
        "operationId": "create-recurring-task",
        "summary": "Create Recurring Task",
        "description": "Create Recurring Task",
        "tags": [
          "Recurring Tasks"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/locations/{locationId}/customFields": {
      "get": {
        "operationId": "get-custom-fields",
        "summary": "Get Custom Fields",
        "description": "Get Custom Fields",
        "tags": [
          "Custom Field"
        ],
        "security": [
          {
            "bearer": [
              "locations/customFields.readonly"
            ]
          }
        ]
      },
      "post": {
        "operationId": "create-custom-field",
        "summary": "Create Custom Field",
        "description": "Create Custom Field",
        "tags": [
          "Custom Field"
        ],
        "security": [
          {
            "bearer": [
              "locations/customFields.write"
            ]
          }
        ]
      }
    },
    "/locations/{locationId}/customFields/{id}": {
      "get": {
        "operationId": "get-custom-field",
        "summary": "Get Custom Field",
        "description": "Get Custom Field",
        "tags": [
          "Custom Field"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "put": {
        "operationId": "update-custom-field",
        "summary": "Update Custom Field",
        "description": "Update Custom Field",
        "tags": [
          "Custom Field"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "delete": {
        "operationId": "delete-custom-field",
        "summary": "Delete Custom Field",
        "description": "Delete Custom Field",
        "tags": [
          "Custom Field"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/locations/{locationId}/customFields/upload": {
      "post": {
        "operationId": "upload-file-customFields",
        "summary": "Uploads File to customFields",
        "description": "Uploads File to customFields",
        "tags": [
          "Custom Field"
        ],
        "security": [
          {
            "bearer": [
              "locations/customFields.write"
            ]
          }
        ]
      }
    },
    "/locations/{locationId}/customValues": {
      "get": {
        "operationId": "get-custom-values",
        "summary": "Get Custom Values",
        "description": "Get Custom Values",
        "tags": [
          "Custom Value"
        ],
        "security": [
          {
            "bearer": [
              "locations/customValues.readonly"
            ]
          }
        ]
      },
      "post": {
        "operationId": "create-custom-value",
        "summary": "Create Custom Value",
        "description": "Create Custom Value",
        "tags": [
          "Custom Value"
        ],
        "security": [
          {
            "bearer": [
              "locations/customValues.write"
            ]
          }
        ]
      }
    },
    "/locations/{locationId}/customValues/{id}": {
      "get": {
        "operationId": "get-custom-value",
        "summary": "Get Custom Value",
        "description": "Get Custom Value",
        "tags": [
          "Custom Value"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "put": {
        "operationId": "update-custom-value",
        "summary": "Update Custom Value",
        "description": "Update Custom Value",
        "tags": [
          "Custom Value"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "delete": {
        "operationId": "delete-custom-value",
        "summary": "Delete Custom Value",
        "description": "Delete Custom Value",
        "tags": [
          "Custom Value"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/locations/{locationId}/timezones": {
      "get": {
        "operationId": "get-timezones",
        "summary": "Fetch Timezones",
        "description": "Fetch the available timezones",
        "tags": [
          "Timezone"
        ],
        "security": [
          {
            "bearer": [
              "locations.readonly"
            ]
          },
          {
            "Location-Access": [
              "locations.readonly"
            ]
          }
        ]
      }
    },
    "/locations/{locationId}/templates": {
      "get": {
        "operationId": "GET-all-or-email-sms-templates",
        "summary": "GET all or email/sms templates",
        "description": "GET all or email/sms templates",
        "tags": [
          "Template"
        ],
        "security": [
          {
            "bearer": [
              "locations/templates.readonly"
            ]
          }
        ]
      }
    },
    "/locations/{locationId}/templates/{id}": {
      "delete": {
        "operationId": "DELETE-an-email-sms-template",
        "summary": "DELETE an email/sms template",
        "description": "DELETE an email/sms template",
        "tags": [
          "Template"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/locations/": {
      "post": {
        "operationId": "create-location",
        "summary": "Create Sub-Account (Formerly Location)",
        "description": "<div>\n                  <p>Create a new Sub-Account (Formerly Location) based on the data provided</p> \n                  <div>\n                    <span style= \"display: inline-block;\n                                width: 25px; height: 25px;\n                                background-color: yellow;\n                                color: black;\n                                font-weight: bold;\n                                font-size: 24px;\n                  [...]",
        "tags": [
          "Sub-Account (Formerly Location)"
        ],
        "security": [
          {
            "Agency-Access": [
              "locations.write"
            ]
          }
        ]
      }
    },
    "/marketplace/billing/charges": {
      "post": {
        "operationId": "charge",
        "summary": "Create a new wallet charge",
        "description": "Create a new wallet charge",
        "tags": [
          "Wallet Charges"
        ],
        "security": [
          {
            "Location-Access-Only": [
              "charges.write"
            ]
          }
        ]
      },
      "get": {
        "operationId": "getCharges",
        "summary": "Get all wallet charges",
        "description": "Get all wallet charges",
        "tags": [
          "Wallet Charges"
        ],
        "security": [
          {
            "Location-Access-Only": [
              "charges.readonly"
            ]
          }
        ]
      }
    },
    "/marketplace/billing/charges/{chargeId}": {
      "delete": {
        "operationId": "deleteCharge",
        "summary": "Delete a wallet charge",
        "description": "Delete a wallet charge",
        "tags": [
          "Wallet Charges"
        ],
        "security": [
          {
            "Location-Access-Only": [
              "charges.write"
            ]
          }
        ]
      },
      "get": {
        "operationId": "getSpecificCharge",
        "summary": "Get specific wallet charge details",
        "description": "Get specific wallet charge details",
        "tags": [
          "Wallet Charges"
        ],
        "security": [
          {
            "Location-Access-Only": [
              "charges.readonly"
            ]
          }
        ]
      }
    },
    "/marketplace/billing/charges/has-funds": {
      "get": {
        "operationId": "hasFunds",
        "summary": "Check if account has sufficient funds",
        "description": "Check if account has sufficient funds",
        "tags": [
          "Wallet Charges"
        ],
        "security": [
          {
            "Location-Access-Only": [
              "charges.readonly"
            ]
          }
        ]
      }
    },
    "/marketplace/app/{appId}/installations": {
      "delete": {
        "operationId": "uninstall-application",
        "summary": "Uninstall an application",
        "description": "Uninstalls an application from your company or a specific location. This will remove the application`s access and stop all its functionalities",
        "security": [
          {
            "Location-Access-Only": []
          },
          {
            "Agency-Access": []
          }
        ],
        "tags": [
          "App Management"
        ]
      },
      "get": {
        "operationId": "get-installer-details",
        "summary": "Get Installer Details",
        "description": "Fetches installer details for the authenticated user. This endpoint returns information about the company, location, user, and installation details associated with the current OAuth token.",
        "tags": [
          "App Management"
        ]
      }
    },
    "/medias/files": {
      "get": {
        "operationId": "fetch-media-content",
        "summary": "Get List of Files/ Folders",
        "description": "Fetches list of files and folders from the media library",
        "security": [
          {
            "Location-Access": [
              "medias.readonly"
            ]
          }
        ],
        "tags": [
          "Medias"
        ]
      }
    },
    "/medias/upload-file": {
      "post": {
        "operationId": "upload-media-content",
        "summary": "Upload File into Media Library",
        "description": "If hosted is set to true then fileUrl is required. Else file is required. If adding a file, maximum allowed is 25 MB",
        "security": [
          {
            "Location-Access": [
              "medias.write"
            ]
          }
        ],
        "tags": [
          "Medias"
        ]
      }
    },
    "/medias/{id}": {
      "delete": {
        "operationId": "delete-media-content",
        "summary": "Delete File or Folder",
        "description": "Deletes specific file or folder from the media library",
        "security": [
          {
            "Location-Access": [
              "medias.write"
            ]
          }
        ],
        "tags": [
          "Medias"
        ]
      },
      "post": {
        "operationId": "update-media-object",
        "summary": "Update File/ Folder",
        "description": "Updates a single file or folder by ID",
        "security": [
          {
            "Location-Access": []
          }
        ],
        "tags": [
          "Medias"
        ]
      }
    },
    "/medias/folder": {
      "post": {
        "operationId": "create-media-folder",
        "summary": "Create Folder",
        "description": "Creates a new folder in the media library",
        "security": [
          {
            "Location-Access": []
          }
        ],
        "tags": [
          "Medias"
        ]
      }
    },
    "/medias/update-files": {
      "put": {
        "operationId": "bulk-update-media-objects",
        "summary": "Bulk Update Files/ Folders",
        "description": "Updates metadata or status of multiple files and folders",
        "security": [
          {
            "Location-Access": []
          }
        ],
        "tags": [
          "Medias"
        ]
      }
    },
    "/medias/delete-files": {
      "put": {
        "operationId": "bulk-delete-media-objects",
        "summary": "Bulk Delete / Trash Files or Folders",
        "description": "Soft-deletes or trashes multiple files and folders in a single request",
        "security": [
          {
            "Location-Access": []
          }
        ],
        "tags": [
          "Medias"
        ]
      }
    },
    "/oauth/token": {
      "post": {
        "operationId": "get-access-token",
        "summary": "Get Access Token",
        "description": "Use Access Tokens to access GoHighLevel resources on behalf of an authenticated location/company.",
        "tags": [
          "OAuth 2.0"
        ]
      }
    },
    "/oauth/locationToken": {
      "post": {
        "operationId": "get-location-access-token",
        "summary": "Get Location Access Token from Agency Token",
        "description": "This API allows you to generate locationAccessToken from AgencyAccessToken",
        "tags": [
          "OAuth 2.0"
        ],
        "security": [
          {
            "Agency-Access-Only": [
              "oauth.write"
            ]
          }
        ]
      }
    },
    "/oauth/installedLocations": {
      "get": {
        "operationId": "get-installed-location",
        "summary": "Get Location where app is installed",
        "description": "This API allows you fetch location where app is installed upon",
        "tags": [
          "OAuth 2.0"
        ],
        "security": [
          {
            "Agency-Access": [
              "oauth.readonly"
            ]
          }
        ]
      }
    },
    "/objects/{key}": {
      "get": {
        "operationId": "get-object-schema-by-key",
        "summary": "Get Object Schema by key / id",
        "description": "Retrieve Object Schema by key or ID. This will return the schema of the custom object, including all its fields and properties. Supported objects include contact, opportunity, business and custom objects.To understand objects and records, please have a look the documentation here : https://doc.clickup.com/8631005/d/h/87cpx-277156/93bf0c2e23177b0",
        "tags": [
          "Object Schema"
        ],
        "security": [
          {
            "bearer": [
              "objects/schema.readonly"
            ]
          }
        ]
      },
      "put": {
        "operationId": "update-custom-object",
        "summary": "Update Object Schema By Key / Id",
        "description": "Update Custom Object Schema  or standard object's like contact, opportunity, business searchable fields. To understand objects and records, please have a look at the documentation here : https://doc.clickup.com/8631005/d/h/87cpx-277156/93bf0c2e23177b0",
        "tags": [
          "Object Schema"
        ],
        "security": [
          {
            "bearer": [
              "objects/schema.write"
            ]
          }
        ]
      }
    },
    "/objects/{schemaKey}/records/{id}": {
      "get": {
        "operationId": "get-record-by-id",
        "summary": "Get Record By Id",
        "description": "Allows you to get a Standard Object like business and custom object record by Id",
        "tags": [
          "Records"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "put": {
        "operationId": "update-object-record",
        "summary": "Update Record",
        "description": "Update a Custom Object Record by Id. Supported Objects are business and custom objects. Documentation Link - https://doc.clickup.com/8631005/d/h/87cpx-277156/93bf0c2e23177b0/87cpx-376296",
        "tags": [
          "Records"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "delete": {
        "operationId": "delete-object-record",
        "summary": "Delete Record",
        "description": "Delete Record By Id . Supported Objects are business and custom objects.",
        "tags": [
          "Records"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/objects/{schemaKey}/records": {
      "post": {
        "operationId": "create-object-record",
        "summary": "Create Record",
        "description": "Create a Custom Object Record. Supported Objects business and custom objects. Documentation Link - https://doc.clickup.com/8631005/d/h/87cpx-277156/93bf0c2e23177b0/87cpx-376296",
        "tags": [
          "Records"
        ],
        "security": [
          {
            "bearer": [
              "objects/record.write"
            ]
          }
        ]
      }
    },
    "/objects/{schemaKey}/records/search": {
      "post": {
        "operationId": "search-object-records",
        "summary": "Search Object Records",
        "description": "Supported Objects are custom objects and standard objects like \"business\". Documentation Link - https://doc.clickup.com/8631005/d/h/87cpx-277156/93bf0c2e23177b0/87cpx-379336",
        "tags": [
          "Search Object Records"
        ],
        "security": [
          {
            "bearer": [
              "objects/record.readonly"
            ]
          }
        ]
      }
    },
    "/objects/": {
      "get": {
        "operationId": "get-object-by-location-id",
        "summary": "Get all objects for a location",
        "description": "Get all objects for a location. Supported Objects are contact, opportunity, business and custom objects.To understand objects and records, please have a look at the documentation here : https://doc.clickup.com/8631005/d/h/87cpx-277156/93bf0c2e23177b0",
        "tags": [
          "Object Schema"
        ],
        "security": [
          {
            "bearer": [
              "objects/schema.readonly"
            ]
          }
        ]
      },
      "post": {
        "operationId": "create-custom-object-schema",
        "summary": "Create Custom Object",
        "description": "Allows you to create a custom object schema. To understand objects and records, please have a look at the documentation here : https://doc.clickup.com/8631005/d/h/87cpx-277156/93bf0c2e23177b0",
        "tags": [
          "Object Schema"
        ],
        "security": [
          {
            "Agency-Access": [
              "objects/schema.write"
            ]
          }
        ]
      }
    },
    "/opportunities/search": {
      "get": {
        "operationId": "search-opportunity",
        "summary": "Search Opportunity",
        "description": "Search Opportunity",
        "tags": [
          "Search"
        ],
        "security": [
          {
            "bearer": [
              "opportunities.readonly"
            ]
          }
        ]
      }
    },
    "/opportunities/pipelines": {
      "get": {
        "operationId": "get-pipelines",
        "summary": "Get Pipelines",
        "description": "Get Pipelines",
        "tags": [
          "Pipelines"
        ],
        "security": [
          {
            "bearer": [
              "opportunities.readonly"
            ]
          }
        ]
      }
    },
    "/opportunities/{id}": {
      "get": {
        "operationId": "get-opportunity",
        "summary": "Get Opportunity",
        "description": "Get Opportunity",
        "tags": [
          "Opportunities"
        ],
        "security": [
          {
            "bearer": [
              "opportunities.readonly"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete-opportunity",
        "summary": "Delete Opportunity",
        "description": "Delete Opportunity",
        "tags": [
          "Opportunities"
        ],
        "security": [
          {
            "bearer": [
              "opportunities.write"
            ]
          }
        ]
      },
      "put": {
        "operationId": "update-opportunity",
        "summary": "Update Opportunity",
        "description": "Update Opportunity",
        "tags": [
          "Opportunities"
        ],
        "security": [
          {
            "bearer": [
              "opportunities.write"
            ]
          }
        ]
      }
    },
    "/opportunities/{id}/status": {
      "put": {
        "operationId": "update-opportunity-status",
        "summary": "Update Opportunity Status",
        "description": "Update Opportunity Status",
        "tags": [
          "Opportunities"
        ],
        "security": [
          {
            "bearer": [
              "opportunities.write"
            ]
          }
        ]
      }
    },
    "/opportunities/upsert": {
      "post": {
        "operationId": "Upsert-opportunity",
        "summary": "Upsert Opportunity",
        "description": "Upsert Opportunity",
        "tags": [
          "Opportunities"
        ],
        "security": [
          {
            "bearer": [
              "opportunities.write"
            ]
          }
        ]
      }
    },
    "/opportunities/{id}/followers": {
      "post": {
        "operationId": "add-followers-opportunity",
        "summary": "Add Followers",
        "description": "Add Followers",
        "tags": [
          "Followers"
        ],
        "security": [
          {
            "bearer": [
              "opportunities.write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "remove-followers-opportunity",
        "summary": "Remove Followers",
        "description": "Remove Followers",
        "tags": [
          "Followers"
        ],
        "security": [
          {
            "bearer": [
              "opportunities.write"
            ]
          }
        ]
      }
    },
    "/opportunities/": {
      "post": {
        "operationId": "create-opportunity",
        "summary": "Create Opportunity",
        "description": "Create Opportunity",
        "tags": [
          "Opportunities"
        ],
        "security": [
          {
            "bearer": [
              "opportunities.write"
            ]
          }
        ]
      }
    },
    "/payments/integrations/provider/whitelabel": {
      "post": {
        "operationId": "create-integration provider",
        "summary": "Create White-label Integration Provider",
        "description": "The \"Create White-label Integration Provider\" API allows adding a new payment provider integration to the system which is built on top of Authorize.net or NMI. Use this endpoint to create a integration provider with the specified details. Ensure that the required information is provided in the request payload. This endpoint can be only invoked using marketplace-app token",
        "tags": [
          "Integrations"
        ],
        "security": [
          {
            "Location-Access": [
              "payments/integration.write"
            ]
          }
        ]
      },
      "get": {
        "operationId": "list-integration-providers",
        "summary": "List White-label Integration Providers",
        "description": "The \"List White-label Integration Providers\" API allows to retrieve a paginated list of integration providers. Customize your results by filtering whitelabel integration providers(which are built directly on top of Authorize.net or NMI) based on name or paginate through the list using the provided query parameters. This endpoint provides a straightforward way to explore and retrieve integration provider information.",
        "tags": [
          "Integrations"
        ],
        "security": [
          {
            "Location-Access": [
              "payments/integration.readonly"
            ]
          }
        ]
      }
    },
    "/payments/orders": {
      "get": {
        "operationId": "list-orders",
        "summary": "List Orders",
        "description": "The \"List Orders\" API allows to retrieve a paginated list of orders. Customize your results by filtering orders based on name, alt type, order status, payment mode, date range, type of source, contact, funnel products or paginate through the list using the provided query parameters. This endpoint provides a straightforward way to explore and retrieve order information.",
        "tags": [
          "Orders"
        ],
        "security": [
          {
            "Location-Access": [
              "payments/orders.readonly"
            ]
          }
        ]
      }
    },
    "/payments/orders/{orderId}": {
      "get": {
        "operationId": "get-order-by-id",
        "summary": "Get Order by ID",
        "description": "The \"Get Order by ID\" API allows to retrieve information for a specific order using its unique identifier. Use this endpoint to fetch details for a single order based on the provided order ID.",
        "tags": [
          "Orders"
        ],
        "security": [
          {
            "Location-Access": [
              "payments/orders.readonly"
            ]
          }
        ]
      }
    },
    "/payments/orders/{orderId}/record-payment": {
      "post": {
        "operationId": "record-order-payment",
        "summary": "Record Order Payment",
        "description": "The \"Record Order Payment\" API allows to record a payment for an order. Use this endpoint to record payment for an order and update the order status to \"Paid\".",
        "tags": [
          "Orders"
        ],
        "security": [
          {
            "Location-Access": [
              "payments/orders.collectPayment"
            ]
          }
        ]
      }
    },
    "/payments/orders/migrate-order-ps": {
      "post": {
        "operationId": "post-migrate-order-payment-status",
        "summary": "migration Endpoint for Order Payment Status",
        "description": "Process to migrate all the older orders and based on the statuses introduce the payment statuses as well",
        "tags": [
          "Orders"
        ],
        "security": [
          {
            "Location-Access": []
          }
        ]
      }
    },
    "/payments/orders/{orderId}/fulfillments": {
      "post": {
        "operationId": "create-order-fulfillment",
        "summary": "Create order fulfillment",
        "description": "The \"Order Fulfillment\" API facilitates the process of fulfilling an order.",
        "tags": [
          "Order fulfillments"
        ],
        "security": [
          {
            "Location-Access": [
              "payments/orders.write"
            ]
          }
        ]
      },
      "get": {
        "operationId": "list-order-fulfillment",
        "summary": "List fulfillment",
        "description": "List all fulfillment history of an order",
        "tags": [
          "Order fulfillments"
        ],
        "security": [
          {
            "Location-Access": [
              "payments/orders.readonly"
            ]
          }
        ]
      }
    },
    "/payments/orders/{orderId}/notes": {
      "get": {
        "operationId": "list-order-notes",
        "summary": "List Order Notes",
        "description": "List all notes of an order",
        "tags": [
          "Order Notes"
        ],
        "security": [
          {
            "Location-Access": []
          }
        ]
      }
    },
    "/payments/transactions": {
      "get": {
        "operationId": "list-transactions",
        "summary": "List Transactions",
        "description": "The \"List Transactions\" API allows to retrieve a paginated list of transactions. Customize your results by filtering transactions based on name, alt type, transaction status, payment mode, date range, type of source, contact, subscription id, entity id or paginate through the list using the provided query parameters. This endpoint provides a straightforward way to explore and retrieve transaction information.",
        "tags": [
          "Transactions"
        ],
        "security": [
          {
            "Location-Access": [
              "payments/transactions.readonly"
            ]
          }
        ]
      }
    },
    "/payments/transactions/{transactionId}": {
      "get": {
        "operationId": "get-transaction-by-id",
        "summary": "Get Transaction by ID",
        "description": "The \"Get Transaction by ID\" API allows to retrieve information for a specific transaction using its unique identifier. Use this endpoint to fetch details for a single transaction based on the provided transaction ID.",
        "tags": [
          "Transactions"
        ],
        "security": [
          {
            "Location-Access": [
              "payments/transactions.readonly"
            ]
          }
        ]
      }
    },
    "/payments/subscriptions": {
      "get": {
        "operationId": "list-subscriptions",
        "summary": "List Subscriptions",
        "description": "The \"List Subscriptions\" API allows to retrieve a paginated list of subscriptions. Customize your results by filtering subscriptions based on name, alt type, subscription status, payment mode, date range, type of source, contact, subscription id, entity id, contact or paginate through the list using the provided query parameters. This endpoint provides a straightforward way to explore and retrieve subscription information.",
        "tags": [
          "Subscriptions"
        ],
        "security": [
          {
            "Location-Access": [
              "payments/subscriptions.readonly"
            ]
          }
        ]
      }
    },
    "/payments/subscriptions/{subscriptionId}": {
      "get": {
        "operationId": "get-subscription-by-id",
        "summary": "Get Subscription by ID",
        "description": "The \"Get Subscription by ID\" API allows to retrieve information for a specific subscription using its unique identifier. Use this endpoint to fetch details for a single subscription based on the provided subscription ID.",
        "tags": [
          "Subscriptions"
        ],
        "security": [
          {
            "Location-Access": [
              "payments/subscriptions.readonly"
            ]
          }
        ]
      }
    },
    "/payments/coupon/list": {
      "get": {
        "operationId": "list-coupons",
        "summary": "List Coupons",
        "description": "The \"List Coupons\" API allows you to retrieve a list of all coupons available in your location. Use this endpoint to view all promotional offers and special discounts for your customers.",
        "tags": [
          "Coupons"
        ],
        "security": [
          {
            "Location-Access": [
              "payments/coupons.readonly"
            ]
          }
        ]
      }
    },
    "/payments/coupon": {
      "post": {
        "operationId": "create-coupon",
        "summary": "Create Coupon",
        "description": "The \"Create Coupon\" API allows you to create a new promotional coupon with customizable parameters such as discount amount, validity period, usage limits, and applicable products. Use this endpoint to set up promotional offers and special discounts for your customers.",
        "tags": [
          "Coupons"
        ],
        "security": [
          {
            "Location-Access": [
              "payments/coupons.write"
            ]
          }
        ]
      },
      "put": {
        "operationId": "update-coupon",
        "summary": "Update Coupon",
        "description": "The \"Update Coupon\" API enables you to modify existing coupon details such as discount values, validity periods, usage limits, and other promotional parameters. Use this endpoint to adjust or extend promotional offers for your customers.",
        "tags": [
          "Coupons"
        ],
        "security": [
          {
            "Location-Access": [
              "payments/coupons.write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete-coupon",
        "summary": "Delete Coupon",
        "description": "The \"Delete Coupon\" API allows you to permanently remove a coupon from your system using its unique identifier. Use this endpoint to discontinue promotional offers or clean up unused coupons. Note that this action cannot be undone.",
        "tags": [
          "Coupons"
        ],
        "security": [
          {
            "Location-Access": [
              "payments/coupons.write"
            ]
          }
        ]
      },
      "get": {
        "operationId": "get-coupon",
        "summary": "Fetch Coupon",
        "description": "The \"Get Coupon Details\" API enables you to retrieve comprehensive information about a specific coupon using either its unique identifier or promotional code. Use this endpoint to view coupon parameters, usage statistics, validity periods, and other promotional details.",
        "tags": [
          "Coupons"
        ],
        "security": [
          {
            "Location-Access": [
              "payments/coupons.readonly"
            ]
          }
        ]
      }
    },
    "/payments/custom-provider/provider": {
      "post": {
        "operationId": "create-integration",
        "summary": "Create new integration",
        "description": "API to create a new association for an app and location",
        "tags": [
          "Custom Provider"
        ],
        "security": [
          {
            "Location-Access": [
              "payments/custom-provider.write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete-integration",
        "summary": "Deleting an existing integration",
        "description": "API to delete an association for an app and location",
        "tags": [
          "Custom Provider"
        ],
        "security": [
          {
            "Location-Access": [
              "payments/custom-provider.write"
            ]
          }
        ]
      }
    },
    "/payments/custom-provider/connect": {
      "get": {
        "operationId": "fetch-config",
        "summary": "Fetch given provider config",
        "description": "API for fetching an existing payment config for given location",
        "tags": [
          "Custom Provider"
        ],
        "security": [
          {
            "Location-Access": [
              "payments/custom-provider.readonly"
            ]
          }
        ]
      },
      "post": {
        "operationId": "create-config",
        "summary": "Create new provider config",
        "description": "API to create a new payment config for given location",
        "tags": [
          "Custom Provider"
        ],
        "security": [
          {
            "Location-Access": [
              "payments/custom-provider.write"
            ]
          }
        ]
      }
    },
    "/payments/custom-provider/disconnect": {
      "post": {
        "operationId": "disconnect-config",
        "summary": "Disconnect existing provider config",
        "description": "API to disconnect an existing payment config for given location",
        "tags": [
          "Custom Provider"
        ],
        "security": [
          {
            "Location-Access": [
              "payments/custom-provider.write"
            ]
          }
        ]
      }
    },
    "/payments/custom-provider/capabilities": {
      "put": {
        "operationId": "custom-provider-marketplace-app-update-capabilities",
        "summary": "Custom-provider marketplace app update capabilities",
        "description": "Toggle capabilities for the marketplace app tied to the OAuth client",
        "tags": [
          "Custom Provider"
        ],
        "security": [
          {
            "Location-Access": [
              "payments/custom-provider.write"
            ]
          }
        ]
      }
    },
    "/phone-system/number-pools": {
      "get": {
        "operationId": "getNumberPoolList",
        "summary": "List Number Pools",
        "description": "Get list of number pools",
        "security": [
          {
            "Location-Access": [
              "numberpools.read"
            ]
          }
        ],
        "tags": [
          "Number Pools"
        ]
      }
    },
    "/phone-system/numbers/location/{locationId}": {
      "get": {
        "operationId": "active-numbers",
        "summary": "List active numbers",
        "description": "Retrieve a paginated list of active phone numbers for a specific location. Supports filtering, pagination, and optional exclusion of number pool assignments.",
        "security": [
          {
            "Location-Access": [
              "phonenumbers.read"
            ]
          }
        ],
        "tags": [
          "Phone Numbers"
        ]
      }
    },
    "/products/bulk-update": {
      "post": {
        "operationId": "bulkUpdate",
        "summary": "Bulk Update Products",
        "description": "API to bulk update products (price, availability, collections, delete)",
        "tags": [
          "Products"
        ],
        "security": [
          {
            "Location-Access": [
              "products.write"
            ]
          }
        ]
      }
    },
    "/products/bulk-update/edit": {
      "post": {
        "operationId": "bulkEdit",
        "summary": "Bulk Edit Products and Prices",
        "description": "API to bulk edit products and their associated prices (max 30 entities)",
        "tags": [
          "Products"
        ]
      }
    },
    "/products/{productId}/price": {
      "post": {
        "operationId": "create-price-for-product",
        "summary": "Create Price for a Product",
        "description": "The \"Create Price for a Product\" API allows adding a new price associated with a specific product to the system. Use this endpoint to create a price with the specified details for a particular product. Ensure that the required information is provided in the request payload.",
        "tags": [
          "Prices"
        ],
        "security": [
          {
            "Location-Access": [
              "products/prices.write"
            ]
          },
          {
            "Agency-Access": [
              "products/prices.write"
            ]
          }
        ]
      },
      "get": {
        "operationId": "list-prices-for-product",
        "summary": "List Prices for a Product",
        "description": "The \"List Prices for a Product\" API allows retrieving a paginated list of prices associated with a specific product. Customize your results by filtering prices or paginate through the list using the provided query parameters.",
        "tags": [
          "Prices"
        ],
        "security": [
          {
            "Location-Access": [
              "products/prices.readonly"
            ]
          },
          {
            "Agency-Access": [
              "products/prices.readonly"
            ]
          }
        ]
      }
    },
    "/products/inventory": {
      "get": {
        "operationId": "get-list-inventory",
        "summary": "List Inventory",
        "description": "The \"List Inventory API allows the user to retrieve a paginated list of inventory items. Use this endpoint to fetch details for multiple items in the inventory based on the provided query parameters.",
        "tags": [
          "Prices"
        ],
        "security": [
          {
            "Location-Access": [
              "products/prices.readonly"
            ]
          },
          {
            "Agency-Access": [
              "products/prices.readonly"
            ]
          }
        ]
      },
      "post": {
        "operationId": "update-inventory",
        "summary": "Update Inventory",
        "description": "The Update Inventory API allows the user to bulk update the inventory for multiple items. Use this endpoint to update the available quantity and out-of-stock purchase settings for multiple items in the inventory.",
        "tags": [
          "Prices"
        ],
        "security": [
          {
            "Location-Access": [
              "products/prices.write"
            ]
          },
          {
            "Agency-Access": [
              "products/prices.write"
            ]
          }
        ]
      }
    },
    "/products/{productId}/price/{priceId}": {
      "get": {
        "operationId": "get-price-by-id-for-product",
        "summary": "Get Price by ID for a Product",
        "description": "The \"Get Price by ID for a Product\" API allows retrieving information for a specific price associated with a particular product using its unique identifier. Use this endpoint to fetch details for a single price based on the provided price ID and product ID.",
        "tags": [
          "Prices"
        ],
        "security": [
          {
            "Location-Access": [
              "products/prices.readonly"
            ]
          },
          {
            "Agency-Access": [
              "products/prices.readonly"
            ]
          }
        ]
      },
      "put": {
        "operationId": "update-price-by-id-for-product",
        "summary": "Update Price by ID for a Product",
        "description": "The \"Update Price by ID for a Product\" API allows modifying information for a specific price associated with a particular product using its unique identifier. Use this endpoint to update details for a single price based on the provided price ID and product ID.",
        "tags": [
          "Prices"
        ],
        "security": [
          {
            "Location-Access": [
              "products/prices.write"
            ]
          },
          {
            "Agency-Access": [
              "products/prices.write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete-price-by-id-for-product",
        "summary": "Delete Price by ID for a Product",
        "description": "The \"Delete Price by ID for a Product\" API allows deleting a specific price associated with a particular product using its unique identifier. Use this endpoint to remove a price from the system.",
        "tags": [
          "Prices"
        ],
        "security": [
          {
            "Location-Access": [
              "products/prices.write"
            ]
          },
          {
            "Agency-Access": [
              "products/prices.write"
            ]
          }
        ]
      }
    },
    "/products/store/{storeId}/stats": {
      "get": {
        "operationId": "get-product-store-stats",
        "summary": "Fetch Product Store Stats",
        "description": "API to fetch the total number of products, included in the store, and excluded from the store and other stats",
        "tags": [
          "Store"
        ],
        "security": [
          {
            "Location-Access": [
              "products.readonly"
            ]
          }
        ]
      }
    },
    "/products/store/{storeId}": {
      "post": {
        "operationId": "update-store-status",
        "summary": "Action to include/exclude the product in store",
        "description": "API to update the status of products in a particular store",
        "tags": [
          "Store"
        ],
        "security": [
          {
            "Location-Access": [
              "products.write"
            ]
          }
        ]
      }
    },
    "/products/store/{storeId}/priority": {
      "post": {
        "operationId": "update-display-priority",
        "summary": "Update product display priorities in store",
        "description": "API to set the display priority of products in a store",
        "tags": [
          "Store"
        ],
        "security": [
          {
            "Location-Access": []
          }
        ]
      }
    },
    "/products/collections": {
      "get": {
        "operationId": "get-product-collection",
        "summary": "Fetch Product Collections",
        "description": "Internal API to fetch the Product Collections",
        "tags": [
          "Collections"
        ],
        "security": [
          {
            "Location-Access": [
              "products/collection.readonly"
            ]
          }
        ]
      },
      "post": {
        "operationId": "create-product-collection",
        "summary": "Create Product Collection",
        "description": "Create a new Product Collection for a specific location",
        "tags": [
          "Collections"
        ],
        "security": [
          {
            "Location-Access": [
              "products/collection.write"
            ]
          }
        ]
      }
    },
    "/products/collections/{collectionId}": {
      "get": {
        "operationId": "get-product-collection-id",
        "summary": "Get Details about individual product collection",
        "description": "Get Details about individual product collection",
        "tags": [
          "Collections"
        ],
        "security": [
          {
            "Location-Access": [
              "products/collection.readonly"
            ]
          }
        ]
      },
      "put": {
        "operationId": "update-product-collection",
        "summary": "Update Product Collection",
        "description": "Update a specific product collection with Id :collectionId",
        "tags": [
          "Collections"
        ],
        "security": [
          {
            "Location-Access": [
              "products/collection.write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete-product-collection",
        "summary": "Delete Product Collection",
        "description": "Delete specific product collection with Id :collectionId",
        "tags": [
          "Collections"
        ],
        "security": [
          {
            "Location-Access": [
              "products/collection.write"
            ]
          }
        ]
      }
    },
    "/products/reviews": {
      "get": {
        "operationId": "get-product-reviews",
        "summary": "Fetch Product Reviews",
        "description": "API to fetch the Product Reviews",
        "tags": [
          "Reviews"
        ],
        "security": [
          {
            "Location-Access": [
              "products.readonly"
            ]
          }
        ]
      }
    },
    "/products/reviews/count": {
      "get": {
        "operationId": "get-reviews-count",
        "summary": "Fetch Review Count as per status",
        "description": "API to fetch the Review Count as per status",
        "tags": [
          "Reviews"
        ],
        "security": [
          {
            "Location-Access": [
              "products.readonly"
            ]
          }
        ]
      }
    },
    "/products/reviews/{reviewId}": {
      "put": {
        "operationId": "update-product-review",
        "summary": "Update Product Reviews",
        "description": "Update status, reply, etc of a particular review",
        "tags": [
          "Reviews"
        ],
        "security": [
          {
            "Location-Access": [
              "products.write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete-product-review",
        "summary": "Delete Product Review",
        "description": "Delete specific product review",
        "tags": [
          "Reviews"
        ],
        "security": [
          {
            "Location-Access": [
              "products.write"
            ]
          }
        ]
      }
    },
    "/products/reviews/bulk-update": {
      "post": {
        "operationId": "bulk-update-product-review",
        "summary": "Update Product Reviews",
        "description": "Update one or multiple product reviews: status, reply, etc.",
        "tags": [
          "Reviews"
        ],
        "security": [
          {
            "Location-Access": [
              "products.write"
            ]
          }
        ]
      }
    },
    "/products/{productId}": {
      "get": {
        "operationId": "get-product-by-id",
        "summary": "Get Product by ID",
        "description": "The \"Get Product by ID\" API allows to retrieve information for a specific product using its unique identifier. Use this endpoint to fetch details for a single product based on the provided product ID.",
        "tags": [
          "Products"
        ],
        "security": [
          {
            "Location-Access": [
              "products.readonly"
            ]
          },
          {
            "Agency-Access": [
              "products.readonly"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete-product-by-id",
        "summary": "Delete Product by ID",
        "description": "The \"Delete Product by ID\" API allows deleting a specific product using its unique identifier. Use this endpoint to remove a product from the system.",
        "tags": [
          "Products"
        ],
        "security": [
          {
            "Location-Access": [
              "products.write"
            ]
          },
          {
            "Agency-Access": [
              "products.write"
            ]
          }
        ]
      },
      "put": {
        "operationId": "update-product-by-id",
        "summary": "Update Product by ID",
        "description": "The \"Update Product by ID\" API allows modifying information for a specific product using its unique identifier. Use this endpoint to update details for a single product based on the provided product ID.",
        "tags": [
          "Products"
        ],
        "security": [
          {
            "Location-Access": [
              "products.write"
            ]
          },
          {
            "Agency-Access": [
              "products.write"
            ]
          }
        ]
      }
    },
    "/products/": {
      "post": {
        "operationId": "create-product",
        "summary": "Create Product",
        "description": "The \"Create Product\" API allows adding a new product to the system. Use this endpoint to create a product with the specified details. Ensure that the required information is provided in the request payload.",
        "tags": [
          "Products"
        ],
        "security": [
          {
            "Location-Access": [
              "products.write"
            ]
          },
          {
            "Agency-Access": [
              "products.write"
            ]
          }
        ]
      },
      "get": {
        "operationId": "list-invoices",
        "summary": "List Products",
        "description": "The \"List Products\" API allows to retrieve a paginated list of products. Customize your results by filtering products based on name or paginate through the list using the provided query parameters. This endpoint provides a straightforward way to explore and retrieve product information.",
        "tags": [
          "Products"
        ],
        "security": [
          {
            "Location-Access": [
              "products.readonly"
            ]
          },
          {
            "Agency-Access": [
              "products.readonly"
            ]
          }
        ]
      }
    },
    "/proposals/document": {
      "get": {
        "operationId": "list-documents-contracts",
        "summary": "List documents",
        "description": "List documents for a location",
        "security": [
          {
            "Location-Access": []
          },
          {
            "Agency-Access": []
          }
        ],
        "tags": [
          "Documents"
        ]
      }
    },
    "/proposals/document/send": {
      "post": {
        "operationId": "send-documents-contracts",
        "summary": "Send document",
        "description": "Send document to a client",
        "security": [
          {
            "Location-Access": []
          },
          {
            "Agency-Access": []
          }
        ],
        "tags": [
          "Documents"
        ]
      }
    },
    "/proposals/templates": {
      "get": {
        "operationId": "list-documents-contracts-templates",
        "summary": "List templates",
        "description": "List document contract templates for a location",
        "security": [
          {
            "Location-Access": []
          },
          {
            "Agency-Access": []
          }
        ],
        "tags": [
          "Templates"
        ]
      }
    },
    "/proposals/templates/send": {
      "post": {
        "operationId": "send-documents-contracts-template",
        "summary": "Send template",
        "description": "Send template to a client",
        "security": [
          {
            "Location-Access": []
          },
          {
            "Agency-Access": []
          }
        ],
        "tags": [
          "Templates"
        ]
      }
    },
    "/saas-api/public-api/locations": {
      "get": {
        "operationId": "locations-deprecated",
        "summary": "Get locations by stripeId with companyId",
        "description": "Get locations by stripeCustomerId or stripeSubscriptionId with companyId",
        "deprecated": true,
        "tags": [
          "Saas"
        ],
        "security": [
          {
            "Agency-Access": []
          }
        ]
      }
    },
    "/saas-api/public-api/update-saas-subscription/{locationId}": {
      "put": {
        "operationId": "update-saas-subscription-deprecated",
        "summary": "Update SaaS subscription",
        "description": "Update SaaS subscription for given locationId and customerId",
        "deprecated": true,
        "tags": [
          "Saas"
        ],
        "security": [
          {
            "Agency-Access": []
          }
        ]
      }
    },
    "/saas-api/public-api/bulk-disable-saas/{companyId}": {
      "post": {
        "operationId": "bulk-disable-saas-deprecated",
        "summary": "Disable SaaS for locations",
        "description": "Disable SaaS for locations for given locationIds",
        "deprecated": true,
        "tags": [
          "Saas"
        ],
        "security": [
          {
            "Agency-Access": []
          }
        ]
      }
    },
    "/saas-api/public-api/enable-saas/{locationId}": {
      "post": {
        "operationId": "enable-saas-location-deprecated",
        "summary": "Enable SaaS for Sub-Account (Formerly Location)",
        "description": "<div>\n                  <p>Enable SaaS for Sub-Account (Formerly Location) based on the data provided</p>\n                  <div>\n                    <span style= \"display: inline-block;\n                                width: 25px; height: 25px;\n                                background-color: yellow;\n                                color: black;\n                                font-weight: bold;\n                                font-size: 24px;\n                [...]",
        "deprecated": true,
        "tags": [
          "Saas"
        ],
        "security": [
          {
            "Agency-Access": []
          }
        ]
      }
    },
    "/saas-api/public-api/pause/{locationId}": {
      "post": {
        "operationId": "pause-location-deprecated",
        "summary": "Pause location",
        "description": "Pause Sub account for given locationId",
        "deprecated": true,
        "tags": [
          "Saas"
        ],
        "security": [
          {
            "Agency-Access": []
          }
        ]
      }
    },
    "/saas-api/public-api/update-rebilling/{companyId}": {
      "post": {
        "operationId": "update-rebilling-deprecated",
        "summary": "Update Rebilling",
        "description": "Bulk update rebilling for given locationIds",
        "deprecated": true,
        "tags": [
          "Saas"
        ],
        "security": [
          {
            "Agency-Access": []
          }
        ]
      }
    },
    "/saas-api/public-api/agency-plans/{companyId}": {
      "get": {
        "operationId": "get-agency-plans-deprecated",
        "summary": "Get Agency Plans",
        "description": "Fetch all agency subscription plans for a given company ID",
        "deprecated": true,
        "tags": [
          "Saas"
        ],
        "security": [
          {
            "Agency-Access": []
          }
        ]
      }
    },
    "/saas-api/public-api/get-saas-subscription/{locationId}": {
      "get": {
        "operationId": "get-location-subscription-deprecated",
        "summary": "Get Location Subscription Details",
        "description": "Fetch subscription details for a specific location from location metadata",
        "deprecated": true,
        "tags": [
          "Saas"
        ],
        "security": [
          {
            "Agency-Access": []
          }
        ]
      }
    },
    "/saas-api/public-api/bulk-enable-saas/{companyId}": {
      "post": {
        "operationId": "bulk-enable-saas-deprecated",
        "summary": "Bulk Enable SaaS",
        "description": "Enable SaaS mode for multiple locations with support for both SaaS v1 and v2",
        "deprecated": true,
        "tags": [
          "Saas"
        ],
        "security": [
          {
            "Agency-Access": []
          }
        ]
      }
    },
    "/saas-api/public-api/saas-locations/{companyId}": {
      "get": {
        "operationId": "get-saas-locations-deprecated",
        "summary": "Get SaaS Locations",
        "description": "Fetch all SaaS-activated locations for a company with pagination",
        "deprecated": true,
        "tags": [
          "Saas"
        ],
        "security": [
          {
            "Agency-Access": []
          }
        ]
      }
    },
    "/saas-api/public-api/saas-plan/{planId}": {
      "get": {
        "operationId": "get-saas-plan-deprecated",
        "summary": "Get SaaS Plan",
        "description": "Fetch a specific SaaS plan by plan ID",
        "deprecated": true,
        "tags": [
          "Saas"
        ],
        "security": [
          {
            "Agency-Access": []
          }
        ]
      }
    },
    "/saas/locations": {
      "get": {
        "operationId": "locations",
        "summary": "Get locations by stripeId with companyId",
        "description": "Get locations by stripeCustomerId or stripeSubscriptionId with companyId",
        "tags": [
          "Saas"
        ],
        "security": [
          {
            "Agency-Access": []
          }
        ]
      }
    },
    "/saas/update-saas-subscription/{locationId}": {
      "put": {
        "operationId": "generate-payment-link",
        "summary": "Update SaaS subscription",
        "description": "Update SaaS subscription for given locationId and customerId",
        "tags": [
          "Saas"
        ],
        "security": [
          {
            "Agency-Access": []
          }
        ]
      }
    },
    "/saas/bulk-disable-saas/{companyId}": {
      "post": {
        "operationId": "bulk-disable-saas",
        "summary": "Disable SaaS for locations",
        "description": "Disable SaaS for locations for given locationIds",
        "tags": [
          "Saas"
        ],
        "security": [
          {
            "Agency-Access": []
          }
        ]
      }
    },
    "/saas/enable-saas/{locationId}": {
      "post": {
        "operationId": "enable-saas-location",
        "summary": "Enable SaaS for Sub-Account (Formerly Location)",
        "description": "<div>\n                  <p>Enable SaaS for Sub-Account (Formerly Location) based on the data provided</p>\n                  <div>\n                    <span style= \"display: inline-block;\n                                width: 25px; height: 25px;\n                                background-color: yellow;\n                                color: black;\n                                font-weight: bold;\n                                font-size: 24px;\n                [...]",
        "tags": [
          "Saas"
        ],
        "security": [
          {
            "Agency-Access": []
          }
        ]
      }
    },
    "/saas/pause/{locationId}": {
      "post": {
        "operationId": "pause-location",
        "summary": "Pause location",
        "description": "Pause Sub account for given locationId",
        "tags": [
          "Saas"
        ],
        "security": [
          {
            "Agency-Access": []
          }
        ]
      }
    },
    "/saas/update-rebilling/{companyId}": {
      "post": {
        "operationId": "update-rebilling",
        "summary": "Update Rebilling",
        "description": "Bulk update rebilling for given locationIds",
        "tags": [
          "Saas"
        ],
        "security": [
          {
            "Agency-Access": []
          }
        ]
      }
    },
    "/saas/agency-plans/{companyId}": {
      "get": {
        "operationId": "get-agency-plans",
        "summary": "Get Agency Plans",
        "description": "Fetch all agency subscription plans for a given company ID",
        "tags": [
          "Saas"
        ],
        "security": [
          {
            "Agency-Access": []
          }
        ]
      }
    },
    "/saas/get-saas-subscription/{locationId}": {
      "get": {
        "operationId": "get-location-subscription",
        "summary": "Get Location Subscription Details",
        "description": "Fetch subscription details for a specific location from location metadata",
        "tags": [
          "Saas"
        ],
        "security": [
          {
            "Agency-Access": []
          }
        ]
      }
    },
    "/saas/bulk-enable-saas/{companyId}": {
      "post": {
        "operationId": "bulk-enable-saas",
        "summary": "Bulk Enable SaaS",
        "description": "Enable SaaS mode for multiple locations with support for both SaaS v1 and v2",
        "tags": [
          "Saas"
        ],
        "security": [
          {
            "Agency-Access": []
          }
        ]
      }
    },
    "/saas/saas-locations/{companyId}": {
      "get": {
        "operationId": "get-saas-locations",
        "summary": "Get SaaS Locations",
        "description": "Fetch all SaaS-activated locations for a company with pagination",
        "tags": [
          "Saas"
        ],
        "security": [
          {
            "Agency-Access": []
          }
        ]
      }
    },
    "/saas/saas-plan/{planId}": {
      "get": {
        "operationId": "get-saas-plan",
        "summary": "Get SaaS Plan",
        "description": "Fetch a specific SaaS plan by plan ID",
        "tags": [
          "Saas"
        ],
        "security": [
          {
            "Agency-Access": []
          }
        ]
      }
    },
    "/snapshots/": {
      "get": {
        "operationId": "get-custom-snapshots",
        "summary": "Get Snapshots",
        "description": "Get a list of all own and imported Snapshots",
        "tags": [
          "Snapshots"
        ],
        "security": [
          {
            "Agency-Access": []
          }
        ]
      }
    },
    "/snapshots/share/link": {
      "post": {
        "operationId": "create-snapshot-share-link",
        "summary": "Create Snapshot Share Link",
        "description": "Create a share link for snapshot",
        "tags": [
          "Snapshots"
        ],
        "security": [
          {
            "Agency-Access": []
          }
        ]
      }
    },
    "/snapshots/snapshot-status/{snapshotId}": {
      "get": {
        "operationId": "get-snapshot-push",
        "summary": "Get Snapshot Push between Dates",
        "description": "Get list of sub-accounts snapshot pushed in time period",
        "tags": [
          "Snapshots"
        ],
        "security": [
          {
            "Agency-Access": []
          }
        ]
      }
    },
    "/snapshots/snapshot-status/{snapshotId}/location/{locationId}": {
      "get": {
        "operationId": "get-latest-snapshot-push",
        "summary": "Get Last Snapshot Push",
        "description": "Get Latest Snapshot Push Status for a location id",
        "tags": [
          "Snapshots"
        ],
        "security": [
          {
            "Agency-Access": []
          }
        ]
      }
    },
    "/social-media-posting/oauth/google/start": {
      "get": {
        "operationId": "start-google-oauth",
        "summary": "Starts OAuth For Google Account",
        "description": "Open the API in a window with appropriate params and headers instead of using the Curl. User is navigated to Google login OAuth screen. On successful login, listen on window object for message where event listener returns data in its callback function. \n  ### Sample code to listen to event data:\n    window.addEventListener('message', \n      function(e) {\n        if (e.data && e.data.page === 'social_media_posting') {\n        const { actionType, page, platform, placem[...]",
        "tags": [
          "Oauth | Google"
        ],
        "security": [
          {
            "bearer": [
              "socialplanner/oauth.readonly"
            ]
          }
        ]
      }
    },
    "/social-media-posting/oauth/{locationId}/google/locations/{accountId}": {
      "get": {
        "operationId": "get-google-locations",
        "summary": "Get google business locations",
        "description": "Get google business locations",
        "tags": [
          "Oauth | Google"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "post": {
        "operationId": "set-google-locations",
        "summary": "Set google business locations",
        "description": "Set google business locations",
        "tags": [
          "Oauth | Google"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/social-media-posting/{locationId}/posts/list": {
      "post": {
        "operationId": "get-posts",
        "summary": "Get posts",
        "description": "Get Posts",
        "tags": [
          "Post"
        ],
        "security": [
          {
            "bearer": [
              "socialplanner/post.readonly"
            ]
          }
        ]
      }
    },
    "/social-media-posting/{locationId}/posts": {
      "post": {
        "operationId": "create-post",
        "summary": "Create post",
        "description": "Create posts for all supported platforms. It is possible to create customized posts per channel by using the same platform account IDs in a request and hitting the create post API multiple times with different summaries and account IDs per platform.\n\nThe content and media limitations, as well as platform rate limiters corresponding to the respective platforms, are provided in the following reference link:\n\n  Link: [Platform Limitations](https://help.leadconnectorhq.co[...]",
        "tags": [
          "Post"
        ],
        "security": [
          {
            "bearer": [
              "socialplanner/post.write"
            ]
          }
        ]
      }
    },
    "/social-media-posting/{locationId}/posts/{id}": {
      "get": {
        "operationId": "get-post",
        "summary": "Get post",
        "description": "Get post",
        "tags": [
          "Post"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "put": {
        "operationId": "edit-post",
        "summary": "Edit post",
        "description": "Create posts for all supported platforms. It is possible to create customized posts per channel by using the same platform account IDs in a request and hitting the create post API multiple times with different summaries and account IDs per platform.\n\nThe content and media limitations, as well as platform rate limiters corresponding to the respective platforms, are provided in the following reference link:\n\n  Link: [Platform Limitations](https://help.leadconnectorhq.co[...]",
        "tags": [
          "Post"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "delete": {
        "operationId": "delete-post",
        "summary": "Delete Post",
        "description": "Delete Post",
        "tags": [
          "Post"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/social-media-posting/{locationId}/posts/bulk-delete": {
      "post": {
        "operationId": "bulk-delete-social-planner-posts",
        "summary": "Bulk Delete Social Planner Posts",
        "description": "Deletes multiple posts based on the provided list of post IDs. \n                  This operation is useful for clearing up large numbers of posts efficiently. \n                  \nNote: \n                  \n1.The maximum number of posts that can be deleted in a single request is '50'.\n                  \n2.However, It will only get deleted in Highlevel database but still\n                   it is recommended to be cautious of this operation.",
        "tags": [
          "Post"
        ]
      }
    },
    "/social-media-posting/{locationId}/accounts": {
      "get": {
        "operationId": "get-account",
        "summary": "Get Accounts",
        "description": "Get list of accounts and groups",
        "tags": [
          "Account"
        ],
        "security": [
          {
            "bearer": [
              "socialplanner/account.readonly"
            ]
          }
        ]
      }
    },
    "/social-media-posting/{locationId}/accounts/{id}": {
      "delete": {
        "operationId": "delete-account",
        "summary": "Delete Account",
        "description": "Delete account and account from group",
        "tags": [
          "Account"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/social-media-posting/oauth/facebook/start": {
      "get": {
        "operationId": "start-facebook-oauth",
        "summary": "Starts OAuth For Facebook Account",
        "description": "Open the API in a window with appropriate params and headers instead of using the Curl. User is navigated to Facebook login OAuth screen. On successful login, listen on window object for message where event listener returns data in its callback function. \n  ### Sample code to listen to event data:\n    window.addEventListener('message', \n      function(e) {\n        if (e.data && e.data.page === 'social_media_posting') {\n        const { actionType, page, platform, plac[...]",
        "tags": [
          "Oauth | Facebook"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/social-media-posting/oauth/{locationId}/facebook/accounts/{accountId}": {
      "get": {
        "operationId": "get-facebook-page-group",
        "summary": "Get facebook pages",
        "description": "Get facebook pages",
        "tags": [
          "Oauth | Facebook"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "post": {
        "operationId": "attach-facebook-page-group",
        "summary": "Attach facebook pages",
        "description": "Attach facebook pages",
        "tags": [
          "Oauth | Facebook"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/social-media-posting/oauth/instagram/start": {
      "get": {
        "operationId": "start-instagram-oauth",
        "summary": "Starts OAuth For Instagram Account",
        "description": "Open the API in a window with appropriate params and headers instead of using the Curl. User is navigated to Instagram login OAuth screen. On successful login, listen on window object for message where event listener returns data in its callback function. \n  ### Sample code to listen to event data:\n    window.addEventListener('message', \n      function(e) {\n        if (e.data && e.data.page === 'social_media_posting') {\n        const { actionType, page, platform, pla[...]",
        "tags": [
          "Oauth | Instagram"
        ],
        "security": [
          {
            "bearer": [
              "socialplanner/oauth.readonly"
            ]
          }
        ]
      }
    },
    "/social-media-posting/oauth/{locationId}/instagram/accounts/{accountId}": {
      "get": {
        "operationId": "get-instagram-page-group",
        "summary": "Get Instagram Professional Accounts",
        "description": "Get Instagram Professional Accounts",
        "tags": [
          "Oauth | Instagram"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "post": {
        "operationId": "attach-instagram-page-group",
        "summary": "Attach Instagram Professional Accounts",
        "description": "Attach Instagram Professional Accounts",
        "tags": [
          "Oauth | Instagram"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/social-media-posting/oauth/linkedin/start": {
      "get": {
        "operationId": "start-linkedin-oauth",
        "summary": "Starts OAuth For LinkedIn Account",
        "description": "Open the API in a window with appropriate params and headers instead of using the Curl. User is navigated to LinkedIn login OAuth screen. On successful login, listen on window object for message where event listener returns data in its callback function. \n  ### Sample code to listen to event data:\n    window.addEventListener('message', \n      function(e) {\n        if (e.data && e.data.page === 'social_media_posting') {\n        const { actionType, page, platform, plac[...]",
        "tags": [
          "Oauth | LinkedIn"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/social-media-posting/oauth/{locationId}/linkedin/accounts/{accountId}": {
      "get": {
        "operationId": "get-linkedin-page-profile",
        "summary": "Get Linkedin pages and profile",
        "description": "Get Linkedin pages and profile",
        "tags": [
          "Oauth | LinkedIn"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "post": {
        "operationId": "attach-linkedin-page-profile",
        "summary": "Attach linkedin pages and profile",
        "description": "Attach linkedin pages and profile",
        "tags": [
          "Oauth | LinkedIn"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/social-media-posting/oauth/twitter/start": {
      "get": {
        "operationId": "start-twitter-oauth",
        "summary": "Starts OAuth For Twitter Account",
        "description": "<div><div>\n  <span style= \"display: inline-block;\n    width: 25px; height: 25px;\n    background-color: red;\n    color: black;\n    font-weight: bold;\n    font-size: 24px;\n    text-align: center;\n    line-height: 20px;\n    border: 2px solid black;\n    border-radius: 20%;\n    margin-right: 10px;\">\n    !\n  </span>\n  <span><strong>As of December 4, 2024, X (formerly Twitter) is no longer supported. We apologise for any inconvenience.</strong></span>\n</div></di[...]",
        "deprecated": true,
        "tags": [
          "Oauth | Twitter"
        ],
        "security": [
          {
            "bearer": [
              "socialplanner/oauth.readonly"
            ]
          }
        ]
      }
    },
    "/social-media-posting/oauth/{locationId}/twitter/accounts/{accountId}": {
      "get": {
        "operationId": "get-twitter-profile",
        "summary": "Get Twitter profile",
        "description": "<div><div>\n  <span style= \"display: inline-block;\n    width: 25px; height: 25px;\n    background-color: red;\n    color: black;\n    font-weight: bold;\n    font-size: 24px;\n    text-align: center;\n    line-height: 20px;\n    border: 2px solid black;\n    border-radius: 20%;\n    margin-right: 10px;\">\n    !\n  </span>\n  <span><strong>As of December 4, 2024, X (formerly Twitter) is no longer supported. We apologise for any inconvenience.</strong></span>\n</div></di[...]",
        "deprecated": true,
        "tags": [
          "Oauth | Twitter"
        ]
      },
      "post": {
        "operationId": "attach-twitter-profile",
        "summary": "Attach Twitter profile",
        "description": "<div><div>\n  <span style= \"display: inline-block;\n    width: 25px; height: 25px;\n    background-color: red;\n    color: black;\n    font-weight: bold;\n    font-size: 24px;\n    text-align: center;\n    line-height: 20px;\n    border: 2px solid black;\n    border-radius: 20%;\n    margin-right: 10px;\">\n    !\n  </span>\n  <span><strong>As of December 4, 2024, X (formerly Twitter) is no longer supported. We apologise for any inconvenience.</strong></span>\n</div></di[...]",
        "deprecated": true,
        "tags": [
          "Oauth | Twitter"
        ]
      }
    },
    "/social-media-posting/{locationId}/csv": {
      "post": {
        "operationId": "upload-csv",
        "summary": "Upload CSV",
        "tags": [
          "CSV"
        ],
        "security": [
          {
            "bearer": [
              "socialplanner/csv.write"
            ]
          }
        ]
      },
      "get": {
        "operationId": "get-upload-status",
        "summary": "Get Upload Status",
        "tags": [
          "CSV"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/social-media-posting/{locationId}/set-accounts": {
      "post": {
        "operationId": "set-accounts",
        "summary": "Set Accounts",
        "tags": [
          "CSV"
        ],
        "security": [
          {
            "bearer": [
              "socialplanner/csv.write"
            ]
          }
        ]
      }
    },
    "/social-media-posting/{locationId}/csv/{id}": {
      "get": {
        "operationId": "get-csv-post",
        "summary": "Get CSV Post",
        "tags": [
          "CSV"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "patch": {
        "operationId": "start-csv-finalize",
        "summary": "Start CSV Finalize",
        "tags": [
          "CSV"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "delete": {
        "operationId": "delete-csv",
        "summary": "Delete CSV",
        "tags": [
          "CSV"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/social-media-posting/{locationId}/csv/{csvId}/post/{postId}": {
      "delete": {
        "operationId": "delete-csv-post",
        "summary": "Delete CSV Post",
        "tags": [
          "CSV"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/social-media-posting/oauth/tiktok/start": {
      "get": {
        "operationId": "start-tiktok-oauth",
        "summary": "Starts OAuth For Tiktok Account",
        "description": "Open the API in a window with appropriate params and headers instead of using the Curl. User is navigated to Tiktok login OAuth screen. On successful login, listen on window object for message where event listener returns data in its callback function. \n  ### Sample code to listen to event data:\n    window.addEventListener('message', \n      function(e) {\n        if (e.data && e.data.page === 'social_media_posting') {\n        const { actionType, page, platform, placem[...]",
        "tags": [
          "Oauth | Tiktok"
        ],
        "security": [
          {
            "bearer": [
              "socialplanner/oauth.readonly"
            ]
          }
        ]
      }
    },
    "/social-media-posting/oauth/{locationId}/tiktok/accounts/{accountId}": {
      "get": {
        "operationId": "get-tiktok-profile",
        "summary": "Get Tiktok profile",
        "description": "Get Tiktok profile",
        "tags": [
          "Oauth | Tiktok"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "post": {
        "operationId": "attach-tiktok-profile",
        "summary": "Attach Tiktok profile",
        "description": "Attach Tiktok profile",
        "tags": [
          "Oauth | Tiktok"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/social-media-posting/oauth/tiktok-business/start": {
      "get": {
        "operationId": "start-tiktok-business-oauth",
        "summary": "Starts OAuth For Tiktok Business Account",
        "description": "Open the API in a window with appropriate params and headers instead of using the Curl. User is navigated to Tiktok-Business login OAuth screen. On successful login, listen on window object for message where event listener returns data in its callback function. \n  ### Sample code to listen to event data:\n    window.addEventListener('message', \n      function(e) {\n        if (e.data && e.data.page === 'social_media_posting') {\n        const { actionType, page, platfor[...]",
        "tags": [
          "Oauth | Tiktok"
        ],
        "security": [
          {
            "bearer": [
              "socialplanner/oauth.readonly"
            ]
          }
        ]
      }
    },
    "/social-media-posting/oauth/{locationId}/tiktok-business/accounts/{accountId}": {
      "get": {
        "operationId": "get-tiktok-business-profile",
        "summary": "Get Tiktok Business profile",
        "description": "Get Tiktok Business profile",
        "tags": [
          "Oauth | Tiktok"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/social-media-posting/{locationId}/categories": {
      "get": {
        "operationId": "get-categories-location-id",
        "summary": "Get categories by location id",
        "tags": [
          "Category"
        ],
        "security": [
          {
            "bearer": [
              "socialplanner/category.readonly"
            ]
          }
        ]
      }
    },
    "/social-media-posting/{locationId}/categories/{id}": {
      "get": {
        "operationId": "get-categories-id",
        "summary": "Get categories by id",
        "tags": [
          "Category"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/social-media-posting/{locationId}/tags": {
      "get": {
        "operationId": "get-tags-location-id",
        "summary": "Get tags by location id",
        "tags": [
          "Tag"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/social-media-posting/{locationId}/tags/details": {
      "post": {
        "operationId": "get-tags-by-ids",
        "summary": "Get tags by ids",
        "tags": [
          "Tag"
        ],
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/social-media-posting/statistics": {
      "post": {
        "operationId": "get-social-media-statistics",
        "summary": "Get Social Media Statistics",
        "description": "Retrieve analytics data for multiple social media accounts. Provides metrics for the last 7 days with comparison to the previous 7 days. Supports filtering by platforms and specific connected accounts.",
        "tags": [
          "Statistics"
        ]
      }
    },
    "/store/shipping-zone": {
      "post": {
        "operationId": "create-shipping-zone",
        "summary": "Create Shipping Zone",
        "description": "The \"Create Shipping Zone\" API allows adding a new shipping zone.",
        "tags": [
          "Shipping Zone"
        ],
        "security": [
          {
            "Location-Access": []
          }
        ]
      },
      "get": {
        "operationId": "list-shipping-zones",
        "summary": "List Shipping Zones",
        "description": "The \"List Shipping Zone\" API allows to retrieve a list of shipping zone.",
        "tags": [
          "Shipping Zone"
        ],
        "security": [
          {
            "Location-Access": []
          }
        ]
      }
    },
    "/store/shipping-zone/{shippingZoneId}": {
      "get": {
        "operationId": "get-shipping-zones",
        "summary": "Get Shipping Zone",
        "description": "The \"List Shipping Zone\" API allows to retrieve a paginated list of shipping zone.",
        "tags": [
          "Shipping Zone"
        ],
        "security": [
          {
            "Location-Access": []
          }
        ]
      },
      "put": {
        "operationId": "update-shipping-zone",
        "summary": "Update Shipping Zone",
        "description": "The \"update Shipping Zone\" API allows update a shipping zone to the system. ",
        "tags": [
          "Shipping Zone"
        ],
        "security": [
          {
            "Location-Access": []
          }
        ]
      },
      "delete": {
        "operationId": "delete-shipping-zone",
        "summary": "Delete shipping zone",
        "description": "Delete specific shipping zone with Id :shippingZoneId",
        "tags": [
          "Shipping Zone"
        ],
        "security": [
          {
            "Location-Access": []
          }
        ]
      }
    },
    "/store/shipping-zone/shipping-rates": {
      "post": {
        "operationId": "get-available-shipping-zones",
        "summary": "Get available shipping rates",
        "description": "This return available shipping rates for country based on order amount",
        "tags": [
          "Shipping Zone"
        ]
      }
    },
    "/store/shipping-zone/{shippingZoneId}/shipping-rate": {
      "post": {
        "operationId": "create-shipping-rate",
        "summary": "Create Shipping Rate",
        "description": "The \"Create Shipping Rate\" API allows adding a new shipping rate.",
        "tags": [
          "Shipping Zone Rates"
        ],
        "security": [
          {
            "Location-Access": []
          }
        ]
      },
      "get": {
        "operationId": "list-shipping-rates",
        "summary": "List Shipping Rates",
        "description": "The \"List Shipping Rate\" API allows to retrieve a list of shipping rate.",
        "tags": [
          "Shipping Zone Rates"
        ],
        "security": [
          {
            "Location-Access": []
          }
        ]
      }
    },
    "/store/shipping-zone/{shippingZoneId}/shipping-rate/{shippingRateId}": {
      "get": {
        "operationId": "get-shipping-rates",
        "summary": "Get Shipping Rate",
        "description": "The \"List Shipping Rate\" API allows to retrieve a paginated list of shipping rate.",
        "tags": [
          "Shipping Zone Rates"
        ],
        "security": [
          {
            "Location-Access": []
          }
        ]
      },
      "put": {
        "operationId": "update-shipping-rate",
        "summary": "Update Shipping Rate",
        "description": "The \"update Shipping Rate\" API allows update a shipping rate to the system. ",
        "tags": [
          "Shipping Zone Rates"
        ],
        "security": [
          {
            "Location-Access": []
          }
        ]
      },
      "delete": {
        "operationId": "delete-shipping-rate",
        "summary": "Delete shipping rate",
        "description": "Delete specific shipping rate with Id :shippingRateId",
        "tags": [
          "Shipping Zone Rates"
        ],
        "security": [
          {
            "Location-Access": []
          }
        ]
      }
    },
    "/store/shipping-carrier": {
      "post": {
        "operationId": "create-shipping-carrier",
        "summary": "Create Shipping Carrier",
        "description": "The \"Create Shipping Carrier\" API allows adding a new shipping carrier.",
        "tags": [
          "Shipping Carrier"
        ],
        "security": [
          {
            "Location-Access": []
          }
        ]
      },
      "get": {
        "operationId": "list-shipping-carriers",
        "summary": "List Shipping Carriers",
        "description": "The \"List Shipping Carrier\" API allows to retrieve a list of shipping carrier.",
        "tags": [
          "Shipping Carrier"
        ],
        "security": [
          {
            "Location-Access": []
          }
        ]
      }
    },
    "/store/shipping-carrier/{shippingCarrierId}": {
      "get": {
        "operationId": "get-shipping-carriers",
        "summary": "Get Shipping Carrier",
        "description": "The \"List Shipping Carrier\" API allows to retrieve a paginated list of shipping carrier.",
        "tags": [
          "Shipping Carrier"
        ],
        "security": [
          {
            "Location-Access": []
          }
        ]
      },
      "put": {
        "operationId": "update-shipping-carrier",
        "summary": "Update Shipping Carrier",
        "description": "The \"update Shipping Carrier\" API allows update a shipping carrier to the system. ",
        "tags": [
          "Shipping Carrier"
        ],
        "security": [
          {
            "Location-Access": []
          }
        ]
      },
      "delete": {
        "operationId": "delete-shipping-carrier",
        "summary": "Delete shipping carrier",
        "description": "Delete specific shipping carrier with Id :shippingCarrierId",
        "tags": [
          "Shipping Carrier"
        ],
        "security": [
          {
            "Location-Access": []
          }
        ]
      }
    },
    "/store/store-setting": {
      "post": {
        "operationId": "create-store-setting",
        "summary": "Create/Update Store Settings",
        "description": "Create or update store settings by altId and altType.",
        "tags": [
          "Store Setting"
        ],
        "security": [
          {
            "Location-Access": []
          }
        ]
      },
      "get": {
        "operationId": "get-store-settings",
        "summary": "Get Store Settings",
        "description": "Get store settings by altId and altType.",
        "tags": [
          "Store Setting"
        ],
        "security": [
          {
            "Location-Access": []
          }
        ]
      }
    },
    "/surveys/submissions": {
      "get": {
        "operationId": "get-surveys-submissions",
        "summary": "Get Surveys Submissions",
        "description": "Get Surveys Submissions",
        "tags": [
          "Surveys"
        ],
        "security": [
          {
            "bearer": [
              "surveys.readonly"
            ]
          }
        ]
      }
    },
    "/surveys/": {
      "get": {
        "operationId": "get-surveys",
        "summary": "Get Surveys",
        "description": "Get Surveys",
        "tags": [
          "Surveys"
        ],
        "security": [
          {
            "bearer": [
              "surveys.readonly"
            ]
          }
        ]
      }
    },
    "/users/search": {
      "get": {
        "operationId": "search-users",
        "summary": "Search Users",
        "description": "Search Users",
        "tags": [
          "Search"
        ],
        "security": [
          {
            "Agency-Access": [
              "users.readonly"
            ]
          },
          {
            "Location-Access": [
              "users.readonly"
            ]
          }
        ]
      }
    },
    "/users/search/filter-by-email": {
      "post": {
        "operationId": "filter-users-by-email",
        "summary": "Filter Users by Email",
        "description": "Filter users by company ID, deleted status, and email array",
        "tags": [
          "Search"
        ],
        "security": [
          {
            "Agency-Access": [
              "users.readonly"
            ]
          },
          {
            "Location-Access": [
              "users.readonly"
            ]
          }
        ]
      }
    },
    "/users/{userId}": {
      "get": {
        "operationId": "get-user",
        "summary": "Get User",
        "description": "Get User",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "Agency-Access": [
              "users.readonly"
            ]
          },
          {
            "Location-Access": [
              "users.readonly"
            ]
          }
        ]
      },
      "put": {
        "operationId": "update-user",
        "summary": "Update User",
        "description": "Update User",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "Agency-Access": [
              "users.write"
            ]
          },
          {
            "Location-Access": [
              "users.write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete-user",
        "summary": "Delete User",
        "description": "Delete User",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "Agency-Access": [
              "users.write"
            ]
          },
          {
            "Location-Access": [
              "users.write"
            ]
          }
        ]
      }
    },
    "/users/": {
      "get": {
        "operationId": "get-user-by-location",
        "summary": "Get User by Location",
        "description": "Get User by Location",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "Location-Access": [
              "users.readonly"
            ]
          }
        ]
      },
      "post": {
        "operationId": "create-user",
        "summary": "Create User",
        "description": "Create User",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "Agency-Access": [
              "users.write"
            ]
          },
          {
            "Location-Access": [
              "users.write"
            ]
          }
        ]
      }
    },
    "/voice-ai/agents": {
      "post": {
        "operationId": "create-agent",
        "summary": "Create Agent",
        "description": "Create a new voice AI agent configuration and settings",
        "tags": [
          "Agents"
        ],
        "security": [
          {
            "bearer": [
              "voice-ai-agents.write"
            ]
          }
        ]
      },
      "get": {
        "operationId": "get-agents",
        "summary": "List Agents",
        "description": "Retrieve a paginated list of agents for given location.",
        "tags": [
          "Agents"
        ],
        "security": [
          {
            "bearer": [
              "voice-ai-agents.readonly"
            ]
          }
        ]
      }
    },
    "/voice-ai/agents/{agentId}": {
      "patch": {
        "operationId": "patch-agent",
        "summary": "Patch Agent",
        "description": "Partially update an existing voice AI agent",
        "tags": [
          "Agents"
        ],
        "security": [
          {
            "bearer": [
              "voice-ai-agents.write"
            ]
          }
        ]
      },
      "get": {
        "operationId": "get-agent",
        "summary": "Get Agent",
        "description": "Retrieve detailed configuration and settings for a specific voice AI agent",
        "tags": [
          "Agents"
        ],
        "security": [
          {
            "bearer": [
              "voice-ai-agents.readonly"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete-agent",
        "summary": "Delete Agent",
        "description": "Delete a voice AI agent and all its configurations",
        "tags": [
          "Agents"
        ],
        "security": [
          {
            "bearer": [
              "voice-ai-agents.write"
            ]
          }
        ]
      }
    },
    "/voice-ai/dashboard/call-logs": {
      "get": {
        "operationId": "get-call-logs",
        "summary": "List Call Logs",
        "description": "Returns call logs for Voice AI agents scoped to a location. Supports filtering by agent, contact, call type, action types, and date range (interpreted in the provided IANA timezone). Also supports sorting and 1-based pagination.",
        "tags": [
          "Dashboard"
        ],
        "security": [
          {
            "bearer": [
              "voice-ai-dashboard.readonly"
            ]
          }
        ]
      }
    },
    "/voice-ai/dashboard/call-logs/{callId}": {
      "get": {
        "operationId": "getCallLog",
        "summary": "Get Call Log",
        "description": "Returns a call log by callId.",
        "tags": [
          "Dashboard"
        ],
        "security": [
          {
            "bearer": [
              "voice-ai-dashboard.readonly"
            ]
          }
        ]
      }
    },
    "/voice-ai/actions": {
      "post": {
        "operationId": "create-action",
        "summary": "Create Agent Action",
        "description": "Create a new action for a voice AI agent. Actions define specific behaviors and capabilities for the agent during calls.",
        "tags": [
          "Actions"
        ],
        "security": [
          {
            "bearer": [
              "voice-ai-agent-goals.write"
            ]
          }
        ]
      }
    },
    "/voice-ai/actions/{actionId}": {
      "put": {
        "operationId": "update-action",
        "summary": "Update Agent Action",
        "description": "Update an existing action for a voice AI agent. Modifies the behavior and configuration of an agent action.",
        "tags": [
          "Actions"
        ],
        "security": [
          {
            "bearer": [
              "voice-ai-agent-goals.write"
            ]
          }
        ]
      },
      "get": {
        "operationId": "get-action",
        "summary": "Get Agent Action",
        "description": "Retrieve details of a specific action by its ID. Returns the action configuration including actionParameters.",
        "tags": [
          "Actions"
        ],
        "security": [
          {
            "bearer": [
              "voice-ai-agent-goals.readonly"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "delete-action",
        "summary": "Delete Agent Action",
        "description": "Delete an existing action from a voice AI agent. This permanently removes the action and its configuration.",
        "tags": [
          "Actions"
        ],
        "security": [
          {
            "bearer": [
              "voice-ai-agent-goals.write"
            ]
          }
        ]
      }
    },
    "/workflows/": {
      "get": {
        "operationId": "get-workflow",
        "summary": "Get Workflow",
        "description": "Get Workflow",
        "tags": [
          "Workflows"
        ],
        "security": [
          {
            "bearer": [
              "workflows.readonly"
            ]
          }
        ]
      }
    }
  },
  "tags": [
    {
      "name": "Account",
      "description": "Documentation for Social Media Posting API",
      "x-module": "social-media-posting"
    },
    {
      "name": "Actions",
      "description": "Documentation for Voice AI API",
      "x-module": "voice-ai"
    },
    {
      "name": "Agency",
      "description": "Documentation for Agency API",
      "x-module": "agencies"
    },
    {
      "name": "Agents",
      "description": "Documentation for Voice AI API",
      "x-module": "voice-ai"
    },
    {
      "name": "App Management",
      "description": "Documentation for Marketplace API",
      "x-module": "marketplace"
    },
    {
      "name": "Appointment Notes",
      "description": "Documentation for Calendars API",
      "x-module": "calendars"
    },
    {
      "name": "Appointments",
      "description": "Documentation for Contacts API",
      "x-module": "contacts"
    },
    {
      "name": "Associations",
      "description": "Documentation for Associations API",
      "x-module": "associations"
    },
    {
      "name": "Blogs",
      "description": "Documentation for Blogs",
      "x-module": "blogs"
    },
    {
      "name": "Bulk",
      "description": "Documentation for Contacts API",
      "x-module": "contacts"
    },
    {
      "name": "Businesses",
      "description": "Documentation for business API",
      "x-module": "businesses"
    },
    {
      "name": "Calendar Events",
      "description": "Documentation for Calendars API",
      "x-module": "calendars"
    },
    {
      "name": "Calendar Groups",
      "description": "Documentation for Calendars API",
      "x-module": "calendars"
    },
    {
      "name": "Calendar Notifications",
      "description": "Documentation for Calendars API",
      "x-module": "calendars"
    },
    {
      "name": "Calendar Resources: Rooms & Equipments",
      "description": "Documentation for Calendars API",
      "x-module": "calendars"
    },
    {
      "name": "Calendars",
      "description": "Documentation for Calendars API",
      "x-module": "calendars"
    },
    {
      "name": "Campaigns",
      "description": "Documentation for campaigns API",
      "x-module": "campaigns"
    },
    {
      "name": "Category",
      "description": "Documentation for Social Media Posting API",
      "x-module": "social-media-posting"
    },
    {
      "name": "Collections",
      "description": "Documentation for products API",
      "x-module": "products"
    },
    {
      "name": "Companies",
      "description": "Documentation for Companies API",
      "x-module": "companies"
    },
    {
      "name": "Contacts",
      "description": "Documentation for Contacts API",
      "x-module": "contacts"
    },
    {
      "name": "contracts",
      "description": "Documentation for Documents and Contracts API",
      "x-module": "proposals"
    },
    {
      "name": "Conversation Channel",
      "description": "Documentation for Sub-Account (Formerly location) API",
      "x-module": "locations"
    },
    {
      "name": "Conversations",
      "description": "Documentation for Conversations API",
      "x-module": "conversations"
    },
    {
      "name": "Coupons",
      "description": "Documentation for payments API",
      "x-module": "payments"
    },
    {
      "name": "Courses",
      "description": "API Service for Courses and Memberships",
      "x-module": "courses"
    },
    {
      "name": "CSV",
      "description": "Documentation for Social Media Posting API",
      "x-module": "social-media-posting"
    },
    {
      "name": "Custom Field",
      "description": "Documentation for Sub-Account (Formerly location) API",
      "x-module": "locations"
    },
    {
      "name": "Custom Field Search",
      "description": "Documentation for Sub-Account (Formerly location) API",
      "x-module": "locations"
    },
    {
      "name": "Custom Fields V2",
      "description": "Custom fields are data points that allow you to capture and store specific information tailored to your business requirements. You can create fields across field types like text, numeric, selection options and special fields like date/time or signature",
      "x-module": "custom-fields"
    },
    {
      "name": "Custom Menu Links",
      "description": "Documentation for Custom menus API",
      "x-module": "custom-menus"
    },
    {
      "name": "Custom Objects Schema",
      "description": "Custom objects are completely customizable objects that allow you to store and manage information tailored to your unique business needs. With custom objects, you can create custom fields, establish relationships, and integrate them into workflows, providing flexibility beyond standard objects like Contacts, Opportunities or Companies.",
      "x-module": "objects"
    },
    {
      "name": "Custom Provider",
      "description": "Documentation for payments API",
      "x-module": "payments"
    },
    {
      "name": "Custom Value",
      "description": "Documentation for Sub-Account (Formerly location) API",
      "x-module": "locations"
    },
    {
      "name": "CUSTOM_FIELDS",
      "description": "Custom fields are data points that allow you to capture and store specific information tailored to your business requirements. You can create fields across field types like text, numeric, selection options and special fields like date/time or signature",
      "x-module": "custom-fields"
    },
    {
      "name": "custom-menus",
      "description": "Documentation for Custom menus API",
      "x-module": "custom-menus"
    },
    {
      "name": "Dashboard",
      "description": "Documentation for Voice AI API",
      "x-module": "voice-ai"
    },
    {
      "name": "documents",
      "description": "Documentation for Documents and Contracts API",
      "x-module": "proposals"
    },
    {
      "name": "ElasticSearch",
      "description": "Documentation for Sub-Account (Formerly location) API",
      "x-module": "locations"
    },
    {
      "name": "Email",
      "description": "Documentation for Conversations API",
      "x-module": "conversations"
    },
    {
      "name": "Email Verification",
      "description": "Documentation for Email ISV API",
      "x-module": "email-isv"
    },
    {
      "name": "Emails",
      "description": "Documentation for emails API",
      "x-module": "emails"
    },
    {
      "name": "Estimate",
      "description": "Documentation for invoice API",
      "x-module": "invoices"
    },
    {
      "name": "Export",
      "description": "Documentation for Opportunities API",
      "x-module": "opportunities"
    },
    {
      "name": "Followers",
      "description": "Documentation for Contacts API",
      "x-module": "contacts"
    },
    {
      "name": "Forms",
      "description": "Documentation for forms API",
      "x-module": "forms"
    },
    {
      "name": "Funnel",
      "description": "Documentation for funnels API",
      "x-module": "funnels"
    },
    {
      "name": "Integrations",
      "description": "Documentation for funnels API",
      "x-module": "funnels"
    },
    {
      "name": "Invoice",
      "description": "Documentation for invoice API",
      "x-module": "invoices"
    },
    {
      "name": "Labs",
      "description": "Documentation for Sub-Account (Formerly location) API",
      "x-module": "locations"
    },
    {
      "name": "Location",
      "description": "Documentation for Sub-Account (Formerly location) API",
      "x-module": "locations"
    },
    {
      "name": "Location Keys",
      "description": "Documentation for Sub-Account (Formerly location) API",
      "x-module": "locations"
    },
    {
      "name": "Location Notes",
      "description": "Documentation for Sub-Account (Formerly location) API",
      "x-module": "locations"
    },
    {
      "name": "Location Search",
      "description": "Documentation for Sub-Account (Formerly location) API",
      "x-module": "locations"
    },
    {
      "name": "Location Tags",
      "description": "Documentation for Sub-Account (Formerly location) API",
      "x-module": "locations"
    },
    {
      "name": "Location Tasks",
      "description": "Documentation for Sub-Account (Formerly location) API",
      "x-module": "locations"
    },
    {
      "name": "Marketplace",
      "description": "Documentation for Marketplace API",
      "x-module": "marketplace"
    },
    {
      "name": "Medias",
      "description": "Documentation for Files API",
      "x-module": "medias"
    },
    {
      "name": "Messages",
      "description": "Documentation for Conversations API",
      "x-module": "conversations"
    },
    {
      "name": "Notes",
      "description": "Documentation for Contacts API",
      "x-module": "contacts"
    },
    {
      "name": "Number Pools",
      "description": "Documentation for number pools management",
      "x-module": "phone-system"
    },
    {
      "name": "Oauth | Facebook",
      "description": "Documentation for Social Media Posting API",
      "x-module": "social-media-posting"
    },
    {
      "name": "Oauth | Google",
      "description": "Documentation for Social Media Posting API",
      "x-module": "social-media-posting"
    },
    {
      "name": "Oauth | Instagram",
      "description": "Documentation for Social Media Posting API",
      "x-module": "social-media-posting"
    },
    {
      "name": "Oauth | LinkedIn",
      "description": "Documentation for Social Media Posting API",
      "x-module": "social-media-posting"
    },
    {
      "name": "Oauth | Tiktok",
      "description": "Documentation for Social Media Posting API",
      "x-module": "social-media-posting"
    },
    {
      "name": "Oauth | Twitter",
      "description": "Documentation for Social Media Posting API",
      "x-module": "social-media-posting"
    },
    {
      "name": "OAuth 2.0",
      "description": "Documentation for OAuth 2.0 API",
      "x-module": "oauth"
    },
    {
      "name": "Object Schema",
      "description": "Custom objects are completely customizable objects that allow you to store and manage information tailored to your unique business needs. With custom objects, you can create custom fields, establish relationships, and integrate them into workflows, providing flexibility beyond standard objects like Contacts, Opportunities or Companies.",
      "x-module": "objects"
    },
    {
      "name": "Opportunities",
      "description": "Documentation for Opportunities API",
      "x-module": "opportunities"
    },
    {
      "name": "Order fulfillments",
      "description": "Documentation for payments API",
      "x-module": "payments"
    },
    {
      "name": "Order Notes",
      "description": "Documentation for payments API",
      "x-module": "payments"
    },
    {
      "name": "Orders",
      "description": "Documentation for payments API",
      "x-module": "payments"
    },
    {
      "name": "Payment Service V1",
      "description": "Documentation for payments API",
      "x-module": "payments"
    },
    {
      "name": "Payments",
      "description": "Documentation for payments API",
      "x-module": "payments"
    },
    {
      "name": "Phone Numbers",
      "description": "Documentation for phone numbers management",
      "x-module": "phone-system"
    },
    {
      "name": "Pipelines",
      "description": "Documentation for Opportunities API",
[...]
